### ISSUE TITLE
Make our docs more actionable

### ISSUE THREAD

**Issue by jgeewax** [googleapis/google-cloud-common#104]
I know we just talked about having the "edit" button next to a bunch of stuff. I'd really like to make our stuff actionable, so the key things I'm seeing are:
1. Edit (contribute back and update stuff that might be off)
2. Ask a question (I understand what this is doing, but I want to make sure I'm using it right, which ultimately will make it's way into the docs)
3. Report an issue (I think something's wrong, but I don't know the fix, or have the time to fix it myself)

And as @stephenplusplus mentioned, this would be on each of the key things:
- Overview
- Description
- Each parameter
- Each example

For each of these, the actions would do something slightly different:
- Edit: Open up the editor in GH (we sort of have this today), but we need to make this work even for people who _don't_ have an active fork.
- Ask: File an issue pre-filled ("Question about .... " in the title, and some pre-filled dynamic text in the body)
- Report: File an issue pre-filled (ie, "Issue with .filter method" in the title, and body with the issue template GH is rolling out)

Ideally we eventually get to the point where the GH issue form can be built into our app (I think we have that somewhere), but for now, just a link to an issue being reported (in a new tab if it's leaving our pages) is a big step up.

**Comment by quartzmo** [comment]
:+1: Sounds great.
