### ISSUE TITLE
Ensure snippets are up to date

### ISSUE THREAD

**Issue by pcostell** [googleapis/google-cloud-common#106]
Is there any way for us to ensure that snippets built using gcloud remain up-to-date? The docs github projects do use travis, but the issue is that if no one upgrades the gcloud library used then snippets will quickly become out of date (i.e. on the [node snippets](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/datastore/package.json) we lock in to `gcloud-node~=0.28.0`).

I don't know what this would look like, but maybe triggering the snippet tests as part of the actual library CI tests with an updated dependency?

**Comment by tseaver** [comment]
https://github.com/GoogleCloudPlatform/gcloud-python/issues/1141 makes it a goal to ensure that the snippets embedded in our Sphinx docs get tested.  We have been discussing just how it should be done, but we mean to integrate it into the CI process.

**Comment by pcostell** [comment]
@tseaver I think this issue is slightly different because these snippets are maintained externally (for `gcloud-python`, here: https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/datastore/api)

For example, right now they [define a dependency][https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/requirements-py27-dev.txt] on `gcloud-python==0.10.1`, which is already a version behind the current published version. This means the samples on https://cloud.google.com/datastore/docs may already be broken.
