### ISSUE TITLE
site: JSON reloading when deeplinking

### ISSUE THREAD

**Issue by callmehiphop** [googleapis/google-cloud-common#112]
Currently if you navigate to a service page (such as [BigQuery](https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.29.0/bigquery)) clicking a method from the method list will re-load the JSON for that particular page. Ideally this would not occur and it would simply transition to the desired method.

**Comment by stephenplusplus** [comment]
For me, clicking a method doesn't actually do anything.

**Comment by quartzmo** [comment]
The links don't work for me either.

@callmehiphop Do you still need to update `types.json` with entries for methods (such as [/docs/v0.29.0/bigquery%23createDataset](https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.29.0/bigquery%23createDataset)) as explained in the description of #109?

**Comment by callmehiphop** [comment]
Haha, yeah I did (and I just did that so it should work now)
