### ISSUE TITLE
Add line numbers to longer code examples

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-common#121]
Above a certain length (@jgeewax suggests 10 non-blank lines of code), examples may benefit from line numbers, so that users may more easily reference specific lines.

**Comment by stephenplusplus** [comment]
SGTM. Just leaving a note here to ask that we don't let the line numbers appear in copy-pasted code-- that's the worst!

**Comment by jgeewax** [comment]
Yep -- line numbers *must* be copy/paste friendly :) 

Firebase did a great job with theirs: https://www.firebase.com/docs/web/api/firebase/authwithoauthtoken.html

**Comment by callmehiphop** [comment]
Interestingly enough, highlightjs [does not support line numbers](http://highlightjs.readthedocs.org/en/latest/line-numbers.html). We may need to find a separate module to handle this for us or else consider switching to a different highlighting module.

**Comment by stephenplusplus** [comment]
Can we do it with css counters? https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Lists_and_Counters/Using_CSS_counters -- http://codepen.io/elomatreb/pen/hbgxp

**Comment by quartzmo** [comment]
It looks like Firebase is using [Prettify](https://github.com/google/code-prettify). I'm not sure how well it supports Ruby. (The readme says, "works passably on Ruby".) I can't find a demo.

**Comment by callmehiphop** [comment]
@stephenplusplus CSS counters look pretty promising!
