### ISSUE TITLE
Pub/Sub emulator - Fix API Conformance Issues

### ISSUE THREAD

**Issue by hbchai** [googleapis/google-cloud-common#129]
- [ ] Fix DeleteTopic not setting subscription topic names to `_deleted-topic_`
- [ ] Fix accepted characters for Subscription and Topic names

According to [API docs](https://github.com/googleapis/googleapis/blob/master/google/pubsub/v1/pubsub.proto).

Reported in #48 by @dhermes.

**Comment by mziccard** [comment]
I also noticed that if I do not provide an `ackDeadlineSeconds` field the emulator defaults it to 60 while according to the [docs](https://github.com/googleapis/googleapis/blob/master/google/pubsub/v1/pubsub.proto#L286) default value should be 10.

**Comment by mziccard** [comment]
Any update on this?

**Comment by hbchai** [comment]
Sorry for the delayed response. I'm going to have some look at this soon.

**Comment by garrettjonesgoogle** [comment]
Hey, checking in again for `google-cloud-java` - any update on the remaining issues?
