### ISSUE TITLE
gcloud should have a client/language agnostic landing page

### ISSUE THREAD

**Issue by asciimike** [googleapis/google-cloud-common#131]
All the individual clients (node, ruby, java, python) have their own github pages (https://googlecloudplatform.github.io/gcloud-{platform}), but there's no https://googlecloudplatform.github.io/gcloud page that captures an overview. This makes it hard to link to gcloud docs from other docs, unless those docs are already language specific (not all are).

We should make such a page :)

**Comment by jgeewax** [comment]
I think we can make a `gcloud-common` landing page for now? Will that work?

**Comment by mcdonamp** [comment]
I think that's fine--it's currently what I link to, so if we got a prettier page with similar content, that would make me happy.
