### ISSUE TITLE
Separate GitHub organizations (per language)

### ISSUE THREAD

**Issue by blowmage** [googleapis/google-cloud-common#139]
In #138 we are discussing some of the challenges for modularizing the gcloud libraries. One of the biggest issues IMO is using a monolithic git repo for all the independent service packages.

Would it be possible to create new organizations, one for each language, and have separate git repos for each independent package? For example, I would love to see a `gcloud-ruby` organization, and a `gcloud-ruby/gcloud-datastore` repo.

I could go on and on about the benefits for making this change... 😉

**Comment by quartzmo** [comment]
Concerns regarding additional management overhead resulting from this approach:

- Combinatorial explosion of language platforms x cloud service offerings
- Uncertainty about where to open issues

**Comment by jonparrott** [comment]
Yeah, what's the benefit of splitting into separate repositories? I can understand splitting into separate packages (this has been mentioned over at gcloud-python), but separate repos for each service doesn't sound fun at first glance.

**Comment by broady** [comment]
Do repos have to be 1:1 with packages? I didn't think so.

**Comment by jgeewax** [comment]
@broady : They definitely don't.

I'm with @jonparrott : I think this will add a significant amount of complexity and organizational overhead. I think the monolithic GH repo (one repo per language) is as much code and issue-reporting segmentation as we want...
