### ISSUE TITLE
Add method links in sidebar

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/google-cloud-common#141]
I don't know how plausible this is, but I believe we need to list the methods available to each type one level deeper:

(not real code that produced this, many methods are missing)
<img width="244" alt="screen shot 2016-06-06 at 7 32 05 pm" src="https://cloud.githubusercontent.com/assets/723048/15841229/7eb69e6e-2c1d-11e6-86ea-0a391ba21420.png">

It can be pretty intimidating landing on the "Storage / Bucket" page for gcloud-node: https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.35.0/storage/bucket. The section at the top that lists the methods just isn't enough, not to mention, it's stuck at the top of the page.

The method names would only appear in the sidebar when the parent page is activated.

**Comment by quartzmo** [comment]
Just a note, in gcloud-ruby, we can have several levels of namespaces before we get to the "leaf" types. Listing methods under these would really be a lot of nav options. See our standard Ruby docs for an example. Also note as a design option (love it or hate it), that these docs have a "tabbed" left nav, with a "methods" tab. 

http://www.rubydoc.info/gems/gcloud/Gcloud/Vision/Annotation/Face/Features/Chin

**Comment by blowmage** [comment]
I would really love to see a full API view of the library, with search for both types and methods.

On our old static docs we had an [API Reference page](http://googlecloudplatform.github.io/gcloud-ruby/docs/master/reference.html) that got us part of the way there. You can click on a type to get a list of all the methods, but we didn't ever get to search.

**Comment by stephenplusplus** [comment]
The full API view is important as well, and searching all of them at once would be great since our APIs are getting pretty large.

I think adding in the methods in the navbar would be a quick win for the casual user who "just needs to upload a file". They would just look for a method named something "upload"-ish in the sidebar and drill right down to where they need to be. (This issue is influenced by this [SO comment](http://stackoverflow.com/questions/37662230/using-firebase-parameters-with-google-cloud-storage-under-node-js#comment62813459_37666503)).

> Just a note, in gcloud-ruby, we can have several levels of namespaces before we get to the "leaf" types. 

That makes sense. Given the goal of making the experience easier, I'm not going to be too bothered by a custom option if necessary.

**Comment by callmehiphop** [comment]
What about top level objects? How would those look? Because you'd essentially have something like

* Storage
  * createBucket
  * Bucket
    * create
  * File

Would we hide methods when they're not directly active.. or?

**Comment by stephenplusplus** [comment]
Yeah, the thought is to just take the methods that are on the right and create quick links to them in the sidebar. So:

- Storage (active page)
  - bucket
  - channel
  - createBucket
  - getBuckets
  - Bucket
  - File
  - Channel

If we need more differentiation, we can add a `#` to the method name:

- Storage (active page)
  - #bucket
  - #channel
  - #createBucket
  - #getBuckets
  - Bucket
  - File
  - Channel

**Comment by callmehiphop** [comment]
I think support for some kind of method symbol would be mandatory. IIRC gcloud-ruby uses the same name for static and instance methods so without the symbol it wouldn't be possible to differentiate.

Also what are your feelings on what @quartzmo suggested about an expandable section (We could call it API Methods or something)?

**Comment by stephenplusplus** [comment]
I'm not a huge fan of the expandable here. I consider this too core of a UX aide to require discovery + another click.
