### ISSUE TITLE
Change usage of "gcloud" to be more specific

### ISSUE THREAD

**Issue by jgeewax** [googleapis/google-cloud-common#142]
Can we go through the site and make sure we don't use "gcloud" in a stand-alone way (ie, call it "gcloud-python" instead of "gcloud")?

These are OK:
- "the gcloud package"
- "the gcloud command-line tool"
- "pip install gcloud"
- "require('gcloud');"

These are not: 
- "gcloud is a client library"
- "gcloud is configured to access GCP services"

Can we go through and replace the stand-alone references with things like "gcloud-python is a client library ..."?

The main ones I can see are on the landing page:
- gcloud (the header) -> gcloud-<language> (ie, gcloud-python)
- "gcloud is a client library" -> "gcloud-python is a client library"
- "gcloud is configured ..." -> "gcloud-python is configured ..."
- "What is the relationship between gcloud and the Google APIs Node.js Client?" --> " ... between gcloud-node and ..."
- "gcloud is built specifically ... " -> "gcloud-node is built specifically ..."

**Comment by stephenplusplus** [comment]
Revert https://github.com/GoogleCloudPlatform/gcloud-node/commit/625adf8352ad5d6f0915a519327eff6d4e3e4800, right? Inspiring issue where user was confused: https://github.com/GoogleCloudPlatform/gcloud-node/issues/1362

**Comment by daspecster** [comment]
@jgeewax, sure sounds like a plan.

**Comment by quartzmo** [comment]
I'll add an issue to do this for `gcloud-ruby`.

**Comment by jgeewax** [comment]
Huge bump on this. Can we fix ?

@stephenplusplus : This isn't a confusion issue. We **cannot** use `gcloud` as a standalone thing. It always needs a modifier ("the gcloud client library", "gcloud-python"), or used in code (`require('gcloud')`), but never just as "gcloud". 

I've listed all the places I noticed it used on its own that need to be changed ASAP.

**Comment by dwsupplee** [comment]
We have been down this path for PHP, as part of our changes we added a new key to the manifest which could be helpful here - https://github.com/GoogleCloudPlatform/gcloud-common/tree/master/site#librarytitle-key

**Comment by stephenplusplus** [comment]
@jgeewax so the answer to my question is yes?

**Comment by daspecster** [comment]
@jgeewax https://github.com/GoogleCloudPlatform/gcloud-python/pull/1845#issuecomment-224989791

**Comment by jgeewax** [comment]
@daspecster : Yes we need that change.

@stephenplusplus : That change only had one instance. In this issue I'm referring to a whole pile of changes... more than just the one...

**Comment by stephenplusplus** [comment]
Yeah, I'm just asking if you want that reverted...

**Comment by jgeewax** [comment]
Yep -- that, and the other things at the top of this issue. Again, this isn't a confusion issue. It's a policy issue.... I can't go into the details in this thread, but we need this changed.

**Comment by quartzmo** [comment]
@jgeewax This includes changing all "Gcloud" usages to "gcloud-ruby", correct?

> Gcloud uses Service Account credentials to connect to Google Cloud services.

**Comment by jgeewax** [comment]
Yes. Or adding a modifier. (ie, "the gcloud client library")
