### ISSUE TITLE
Make previewing docs easier

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/google-cloud-common#143]
Hey, I know I opened this topic before, but I'm still struggling to get the site running.

The current docs are here: https://github.com/GoogleCloudPlatform/gcloud-common/tree/9b6058160bd9ceec6ce7068e4340e2340db2b5fc/site#previewing-locally

I've been trying, and still haven't figured out how to copy (symlink?) files to (from?) the gcloud-node gh-pages branch.

My directory structure matches that from the guide:

```
gcloud-common/site/src
 ├─── app # front-end application files
 ├─── assets # images, etc.
 ├─── versions # JSON content folder
 |     └─── v0.28.0 # one folder per release
 |           ├─── toc.json # table of contents for this version
 |           ├─── types.json # list of custom types for this version
 |           └─── storage # one folder per service
 |                 ├─── index.json # one file per class/module/etc.
 |                 └─── bucket.json
 ├─── index.html
 └─── manifest.json
```

Except I had to use `gcloud-common/site/src/json` instead of `gcloud-common/site/src/versions`.

Is it possible to create dummy JSON files / whatever else we leave holes for, so that this repo has everything it needs to run? Maybe just freeze a couple versions of `gcloud-node` and drop them into this repo?

**Comment by daspecster** [comment]
It would be nice to have working examples of all the different features.

I've had similar issues as I've been working on the python docs. It's been something different each time though.

What does your `manifest.json` look like?

Also, @callmehiphop had me uncomment this line to figure out issues.
https://github.com/GoogleCloudPlatform/gcloud-common/blob/master/site/src/app/index.run.js#L14

**Comment by stephenplusplus** [comment]
I forgot to fast-forward master, so I'm going to remove my notes about the errors I was getting.

**Comment by callmehiphop** [comment]
I think your confusion comes from the fact that you can configure the name of the folder the JSON lives in. If you're copying gcloud-node data then the folder should be called JSON (this is all dictated in the manifest.json). Perhaps we should just remove that configuration, since it's caused more confusion than anything.

If you want to add some dummy JSON, please feel free. I put the <kbd>json</kbd> in our gitignore, so you could just copy and paste it locally and be done with it otherwise.

**Comment by stephenplusplus** [comment]
Sounds good, I'll try to dummy it up. The goal is to make it easier for people to help our issue backlog by making it simply "clone repo && cd site && gulp serve".
