### ISSUE TITLE
Defining 1.0.0-beta1

### ISSUE THREAD

**Issue by jgeewax** [googleapis/google-cloud-common#144]
Related to https://github.com/GoogleCloudPlatform/gcloud-common/issues/49

Just keeping track here of what's done and not done for hitting a 1.0.0-beta milestone

| Thing | .NET | Go | Java | Node | PHP | Python | Ruby |
| --- | --- | --- | --- | --- | --- | --- | --- |
| Installation is one-line | ? | ✓ | ✓ | ✓ | ✓ | ✓ | ✓ |
| Snippets for all methods | ? | ? | ? | ✓ | ? | ? | ? |
| Testing at 70%+ coverage | ? | ? | ? | ? | ? | ? | ? |
| Link from cloud.google.com | ? | ? | ? | ? | ? | ? | ? |
| Covers 5 key APIs | ? | ✓ | ? | ✓ | ? | ✓ | ✓ |
| Confident in stability of 5 APIs | ? | ? | ? | ? | ? | ? | ? |
| README mentions APIs | ? | ? | ? | ? | ? | ? | ? |
| README has example per API | ? | ? | ? | ? | ? | ? | ? |
| README points to auth how-to | ? | ? | ? | ? | ? | ? | ? |
| User-agent header | ? | ? | ? | ✓ | ? | ? | ? |

---
- 5 key APIs are Datastore, Storage, Pub/Sub, BigQuery, and Logging

**Comment by jgeewax** [comment]
@stephenplusplus : Can you tell me which of these things are done for gcloud-node ?

**Comment by stephenplusplus** [comment]
Is there an official auth how-to, or just "some kind of doc that explains auth"? I'm confident in the stability. No doubt we will continue to find bugs and make improvements, but I don't know that we will ever avoid this. A deep dive by API representatives would be helpful.

**Comment by jgeewax** [comment]
> Is there an official auth how-to, or just "some kind of doc that explains auth"?

Does the README explain how to deal with auth (ie, showing keyfiles, screenshot page of how to create service accounts, etc)? I think yes.

**Comment by daspecster** [comment]
@jgeewax 
- Testing at 70%+ coverage `gcloud-python` has over 70% test [coverage](https://coveralls.io/github/GoogleCloudPlatform/gcloud-python)
- [Link from cloud.google.com](https://cloud.google.com/python/apis)?
- I think the [README](https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/README.rst) has the items mentioned.
- Not sure if [this](https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/gcloud/connection.py#L66) is what you mean for the `user-agent` item.
