### ISSUE TITLE
Update mentions of "Cloud Logging" to "Stackdriver Logging"

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-common#147]
The [official docs](https://cloud.google.com/logging/docs) now use "Stackdriver Logging" in all API descriptions. For example:

>  If omitted, Stackdriver Logging will use the time the log entry is received.

Update all gcloud-\* Logging docs to match.

**Comment by waprin** [comment]
Also need the same changes for Monitoring

**Comment by waprin** [comment]
For reference:

Long Name -> Short Name 
----------------------------------
Stackdriver Logging -> Logging
Stackdriver Monitoring -> Monitoring
Stackdriver Trace -> Trace
Stackdriver Debugger -> Debugger
Stackdriver Error Reporting -> Error Reporting

Currently we only have clients for Logging and Python Monitoring but will eventually need them all.

/cc @sharbison3

**Comment by jba** [comment]
Done in the new logging client (not yet published).
