### ISSUE TITLE
Can Translate's language detection return multiple detection objects for one text?

### ISSUE THREAD

**Issue by mziccard** [googleapis/google-cloud-common#148]
Google Translate can be used to detect the language by doing:

```
GET https://www.googleapis.com/language/translate/v2/detect?key=<mykey>&q=soy
```

Which returns the following JSON:

``` json
{
 "data": {
  "detections": [
   [
    {
     "language": "es",
     "isReliable": false,
     "confidence": 0.81496066
    }
   ]
  ]
 }
}
```

From the JSON structure it seems that more than one "detection" objects could be returned for a single text (in this case `soy`). I would expect a JSON like the following to be possible:

``` json
{
 "data": {
  "detections": [
   [
    {
     "language": "es",
     "isReliable": false,
     "confidence": 0.81496066
    },
    {
     "language": "en",
     "isReliable": false,
     "confidence": 0.222
    }
   ]
  ]
 }
}
```

As a matter of fact, it seems that only one "detection" object is returned for one `q=text`, regardless of the text being "legal" in multiple languages. AFAIK `gcloud-python` and `gcloud-node` rely on this assumption and always return only a single "detection" object for each text.

@jgeewax it would be nice to have someone from the translate service to confirm that it's safe to assume that no more than one "detection" object can be returned for each `q=text`. And that this won't change any time soon.

**Comment by jgeewax** [comment]
I'm pretty sure the multiple detections only happen when there are multiple strings provided... I'll double check with the Translate team though.....
