### ISSUE TITLE
Worthwhile to have testing on our deps?

### ISSUE THREAD

**Issue by jgeewax** [googleapis/google-cloud-common#149]
https://dependencyci.com/

/cc @stephenplusplus @tseaver

**Comment by stephenplusplus** [comment]
👍 https://dependencyci.com/github/GoogleCloudPlatform/gcloud-node/builds/1

**Comment by blowmage** [comment]
https://dependencyci.com/github/GoogleCloudPlatform/gcloud-ruby/builds/1

**Comment by tseaver** [comment]
I enabled it:

  https://dependencyci.com/github/GoogleCloudPlatform/gcloud-python/builds/1

but it claims `0 dependencies` in our `setup.py`.

**Comment by daspecster** [comment]
@tseaver https://github.com/dependencyci/support/issues/11

**Comment by mziccard** [comment]
[Gave it a try](https://dependencyci.com/github/GoogleCloudPlatform/gcloud-java) but seems to fail for maven projects. Contacted the support [here](https://github.com/dependencyci/support/issues/32).
