### ISSUE TITLE
Add link to dotnet docs in all other platforms

### ISSUE THREAD

**Issue by jskeet** [googleapis/google-cloud-common#151]
The google-cloud-dotnet repo has a landing page in the site of the other gcloud sites now:
http://googlecloudplatform.github.io/google-cloud-dotnet

The other sites should link to it, using the [.NET svg](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/gh-pages/1.0.0-beta01/img/icon-lang-dotnet.svg) for an icon.

Sample HTML:

```
<li>
    <a href="#" title=".NET docs page">
        <img src="img/icon-lang-dotnet.svg" alt=".NET icon" class="menu-icon" width="24" height="24" />
            .NET
    </a>
</li>
```

**Comment by jgeewax** [comment]
Fixed in Python -- not fixed everywhere else yet :)

**Comment by daspecster** [comment]
Oops! I didn't think that putting 'closes' in the PR comments actually worked, I thought it had to be in the commit message. My bad.

**Comment by quartzmo** [comment]
gcloud-ruby will upgrade to the newest gcloud-common/site once it is ready. (/cc @callmehiphop)

**Comment by callmehiphop** [comment]
gcloud-common site now includes .NET! :)

**Comment by quartzmo** [comment]
@callmehiphop @jgeewax The shared site made this virtually no work for gcloud-ruby.

**Comment by jgeewax** [comment]
Yay :) /cc @jskeet

**Comment by dwsupplee** [comment]
[gcloud-php](https://googlecloudplatform.github.io/gcloud-php/#/) now includes .NET as well :)

**Comment by jskeet** [comment]
This looks like it's nearly done, but gcloud-java and gcloud-python have put .NET at the bottom, whereas the other four (including .NET) have put it at the top. Additionally, gcloud-python is missing PHP.

**Comment by dhermes** [comment]
RE: bottom, does it matter? Should it be alphabetical or something?
RE: PHP in `gcloud-python`, happy to add, but it doesn't seem to be germane to this issue?

**Comment by jskeet** [comment]
@dhermes: Everything else is alphabetical, and I've been viewing "." as coming before "J". But I think it *does* matter that we're consistent... I would expect users to think of this as a single fixed menu which changes the rest of the page. The fact that it's served separately for each platform is an implementation issue. The order switching is not a great experience.

The fact that PHP is missing was just something I happened to notice when comparing them all, and thought it might be easily fixed while adjusting the ordering.

**Comment by jgeewax** [comment]
i agree that it matters that we be consistent.

and we should open an issue on gcloud-python to add php ... or... shouldn't
this be fixed now that we're using gcloud-common/site @daspecster

**Comment by daspecster** [comment]
@jgeewax, you're correct we have PHP since we're using the gcloud-common/site now.
