### ISSUE TITLE
Individual Package Documentation Proposal

### ISSUE THREAD

**Issue by blowmage** [googleapis/google-cloud-common#159]
This week the gcloud-ruby repo switched from a monolithic package to individual packages. This move is a pretty radical change, and I think a similar change can be made in the angular application to support it. I understand and respect the desire to change the angular application in an interative and step-wise manner, but I have some reservations about the direction it is now going and the "bundled" package concept.

I figured I would attempt to describe some of the ideas I had about what a non-monolithic documentation site could offer. I started down this line of thinking when I saw one of the earliest mockups for the new site. It seemed to me that the existing side navigation and the package switcher served the same purpose, and would ultimately be confusing to users.

![google-cloud-mockup-annotated](https://cloud.githubusercontent.com/assets/730/17449359/2f8b1012-5b17-11e6-9a10-f601e2d77796.jpg)

What if these two concepts were merged? What if the documentation were bundled not by duplicating documentation in different packages? But by making the angular application aware of multiple packages? What if it allowed users to select different versions of each package? v0.20.0 of Datastore along side v0.13.0 of BigQuery? What if it looked like this?

![google cloud overview](https://cloud.githubusercontent.com/assets/730/17449390/5f7551f2-5b17-11e6-8552-876a2c2d69f1.png)

Clicking on a package would open the packages TOC navigation. In this version of the BigQuery package we added the `Schema` class to the package and TOC. Previous versions maintain their own TOC.

![bigquery overview](https://cloud.githubusercontent.com/assets/730/17449440/b8960e70-5b17-11e6-9496-475a39f936ea.png)

Clicking a package's version would open a menu, so the user could view a specific version. We can also label each version as either the latest release or a previous release.

![bigquery chooser](https://cloud.githubusercontent.com/assets/730/17449455/e039da6a-5b17-11e6-8cd5-2dfbc85aab17.png)

Viewing an older version will display that version's TOC. Notice that `Schema` is not listed, as this version of the library did not have it.

![bigquery v0 13 0 overview](https://cloud.githubusercontent.com/assets/730/17449508/47349d68-5b18-11e6-9e1b-61c9816e8922.png)

Because the angular application is aware of different packages and their respective versions, it can aid the user as they try to navigate them. One way is to prompt the user to change versions when looking for a structure that does not exist in the version they are in.

![bigquery v0 13 0 404](https://cloud.githubusercontent.com/assets/730/17449540/7c8aa5d4-5b18-11e6-963e-f3b36c6babf3.png)

My intention is to help lay out a vision. I think we have a great opportunity to really help users find information in a way that supports the move to individual packages. Hopefully this proposal helps by presenting some ideas not considered before, or prompts even newer ideas in others.

**Comment by callmehiphop** [comment]
So my understanding is that we create a version dropdown for every module and when the `Google Cloud` version is changed, then all the individual service versions change to what is available within that umbrella package. Does that sound right?

**Comment by blowmage** [comment]
Yeah, that could work. The angular app would have to know what the dependencies were for the individual gems though. For example, let's assume `google-cloud` 1.0 depended on `google-cloud-datastore` ^1.0, and then `google-cloud` 1.1 depended on `google-cloud-datastore` ^2.0. The angular app could switch datastore versions when changing the google-cloud version, and/or alert the user when switching to a version of datastore is not compatible with google-cloud.

**Comment by blowmage** [comment]
I should also add that the gcloud-ruby version of `google-cloud` package contains no code, it only defines dependencies. So I think we would be okay with the documentation site treating that package a little differently than the others. Not sure how the other languages are going to be handling the umbrella package though.

The gcloud-ruby version of `google-cloud` contains no code because we want to allow users to choose not to use the umbrella package, and instead depend on only the service packages they want to use. So the `google-cloud-core` package contains all the code that is shared across services.

**Comment by tseaver** [comment]
@blowmage We haven't begun to implement it yet for Python, but that is what we plan, as well.

**Comment by callmehiphop** [comment]
> It seemed to me that the existing side navigation and the package switcher served the same purpose, and would ultimately be confusing to users.

So just to clarify, the two menu's you labeled in your first image are not one in the same. Switching between the packages would change the side navigation to what APIs are available within said package.

<img width="1012" alt="screen shot 2016-08-07 at 1 40 13 pm" src="https://cloud.githubusercontent.com/assets/1707267/17464108/a4268512-5ca4-11e6-884f-8170b559defc.png">
<img width="1012" alt="screen shot 2016-08-07 at 1 40 03 pm" src="https://cloud.githubusercontent.com/assets/1707267/17464110/a675a8ca-5ca4-11e6-9fb3-7cbb0a36fdac.png">

Aside from that, I think what you've put together would work great for users of the individual packages. What I would like to see more explanation of would be the flows that users of the bundled package would go through. 

Pretend that I belong to a team of developers that use version `v1.1.0` of the `google-cloud` (bundle) package.

How do I..

* share links to developers on my team for our specific package version?
* navigate to the corresponding version of the Storage package without having to dig though my installed modules dependency list?

**Comment by blowmage** [comment]
> So just to clarify, the two menu's you labeled in your first image are not one in the same. Switching between the packages would change the side navigation to what APIs are available within said package.

Yes, agreed. We know that, but will users? In retrospect I should have communicated this point better. My point is that the user is presented with two nearly identical lists of services. Will they know which one to choose? Is the difference between the two lists meaningful enough to present the choice to the user? I suspect some users will be confused as a result of the choice, and we have an opportunity to rethink the user experience.

> How do I..

Ah, sweet specifics! Now you are talking my language! Here is option. I'm not wedded to it, but I think it would work.

The current documentation URL for BigQuery Dataset is:

https://googlecloudplatform.github.io/gcloud-ruby/#/docs/v0.12.1/gcloud/bigquery/dataset

In the angular app we define a route for this URL that is equivalent to: `docs/{version}/{path}`. But with the move from monolithic package to individual packages we now have two different concepts: the umbrella package and the individual package. I think we can identify both in the URL.

In the current URL we don't list the main package name in the URL, so I don't think we need to do that in the future URL. But we will need to be able to list the individual package name, version, and path. So what about this? `docs/{umbrella_version}/{individual_package}/{individual_version}/{individual_path}`

> * share links to developers on my team for our specific package version?

This will look the same as the current URL for a specific version: `docs/v1.1.0` It should know what dependencies are present in that version and show the latest matching version of each individual package.

> * navigate to the corresponding version of the Storage package without having to dig though my installed modules dependency list?

Click on "Storage" in the side navigation. This will switch the route to `docs/v1.1.0/storage/latest/`. The route for bucket could be `docs/v1.1.0/storage/latest/bucket`.

When opening the version menu for Storage the app can highlight the versions that are allowed with the umbrella package v1.1.0.
