### ISSUE TITLE
Should we define an env variable to hold API key?

### ISSUE THREAD

**Issue by mziccard** [googleapis/google-cloud-common#164]
We now look into `GOOGLE_APPLICATION_CREDENTIALS` for JSON credentials. Some services (translate) authenticate via an API key, should we define an analogous and common env variable where users can put their API key? If you already support such a variable, would you mind sharing its name?

**Comment by tseaver** [comment]
At the library level, `gcloud-python` doesn't sniff the API key:  we have the application pass it into the constructor for the client.  For system testing, we use the `GCLOUD_TESTS_API_KEY` environment variable to hold the key.

**Comment by mziccard** [comment]
> At the library level, gcloud-python doesn't sniff the API key

How would you see an API key to look for at the library level? Something like `GOOGLE_API_KEY`?

**Comment by tseaver** [comment]
`GOOGLE_API_KEY` SGTM.  I've opened an issue to add support for that in `gcloud-python`.

**Comment by quartzmo** [comment]
For the Translate API, [`gcloud-ruby` looks for](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/master/google-cloud-translate/lib/google-cloud-translate.rb#L110) `GOOGLE_CLOUD_KEY` (and `TRANSLATE_KEY `). We could change it, but that's what we have.
