### ISSUE TITLE
URLs not containing an explicit version drop their "method" argument

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/google-cloud-common#166]
_From @ace-n on August 19, 2016 3:4_

For example, [this link](https://googlecloudplatform.github.io/gcloud-node/#/docs/google-cloud/latest/storage/bucket?method=acl.add) to a non-specific version has a method argument attached to it - but it _isn't_ honored.

[This link](https://googlecloudplatform.github.io/gcloud-node/#/docs/google-cloud/0.38.3/storage/bucket?method=acl.add) is specific to a version - so its method argument _is_ honored.

_Copied from original issue: GoogleCloudPlatform/gcloud-node#1511_

**Comment by ace-n** [comment]
cc @jmdobry
