### ISSUE TITLE
On renaming gcloud-* to google-cloud-*: GCLOUD_ env variables

### ISSUE THREAD

**Issue by mziccard** [googleapis/google-cloud-common#171]
In our `gcloud-*` libraries we have a number of environment variables that start with the prefix `GCLOUD_*`. Should we also rename such variables to `GOOGLE_CLOUD_*` while renaming `gcloud-*` to `google-cloud-*`?

I see gcloud-node guys kept `GCLOUD_*` names (/cc @callmehiphop @stephenplusplus). Do we have an common strategy on this?

**Comment by blowmage** [comment]
We have switched gcloud-ruby to use `GOOGLE_CLOUD_` as the main prefix. `GCLOUD_` will also be used but we left that undocumented for now.
