### ISSUE TITLE
BigQuery parameterization

### ISSUE THREAD

**Issue by jskeet** [googleapis/google-cloud-common#176]
The BigQuery underlying API has no concept of parameterization as far as I can see - it's up to the client to construct SQL appropriately, escaping values appropriately. I haven't seen any signs of client libraries introducing parameterization themselves.

I'm reluctant to add parameterization _just_ to the C# BigQuery library, but it feels like it would be worth doing consistently across platforms. Has anyone else had any thoughts/plans around this?

**Comment by quartzmo** [comment]
Sounds like a great idea to me. @blowmage?

**Comment by blowmage** [comment]
I'm not really sure if the existing ruby API ([query](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.20.0/google/cloud/bigquery/dataset?method=query-instance)/[query_job](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.20.0/google/cloud/bigquery/dataset?method=query_job-instance)) will support query parameters along with the existing optional arguments. So to support this we might need to break backwards compatibility. But maybe not.

Are we talking positional parameters?

```ruby
data = bigquery.query "SELECT * FROM my_table WHERE NAME = ?", "Mike", cache: false
```

Or named parameters?

```ruby
data = bigquery.query "SELECT * FROM my_table WHERE NAME = :name", name: "Mike", cache: false
```

**Comment by jskeet** [comment]
> Named or positional parameters?

Either or both :) This is where it would be good to be consistent across client platforms, IMO.

**Comment by blowmage** [comment]
Agree it would be good to be consistent across platforms.

Perhaps we should make it consistent with how the library handles GQL bindings. For example, google-cloud-ruby has [`GqlQuery`](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.20.0/google/cloud/datastore/gqlquery) that supports both named and positional bindings, but `Dataset` has a helper to create the object with named bindings.

```ruby
gql_query = datastore.gql "SELECT * FROM Task WHERE done = @done", done: false
tasks = datastore.run gql_query
```

But the big difference is that BigQuery doesn't have a dedicated query object... yet.

**Comment by jskeet** [comment]
Yes, modelling this on GQL makes sense to me. I can see that it could be tricky to reliably parse a textual query and extract the parameters however - getting that behaviour identical on every platform. (For example, we'd need to make sure we didn't treat `WHERE done = '@done'` as using a parameter, just as a trivial one...)

**Comment by mberlyant** [comment]
BigQuery jobs.insert and jobs.query APIs supports now parameters

**Comment by jskeet** [comment]
Wow - that's huge. New top priority feature :)

**Comment by jba** [comment]
I can't find any doc, other than the [query job reference](https://cloud.google.com/bigquery/docs/reference/v2/jobs/query), where it's marked experimental.

**Comment by jba** [comment]
We learned from internal communication that query parameters are real and here to stay.
