### ISSUE TITLE
Template for issue that touches all repositories?

### ISSUE THREAD

**Issue by jgeewax** [googleapis/google-cloud-common#18]
I'm finding a lot of the gcloud-common (or gcloud-meta) issues involved all the repositories. Maybe it's worthwhile to have a template for these so that everyone can copy that?

Something like.....

---

General description here

Options:
- Option 1
- Option 2
- ...

Votes (to be updated by creator / admin based on comments)

| Who | for language | Vote |
| --- | --- | --- |
| @okdave | Go | Option 1 |
| @aozarov | Java | Option 1 |
| @mziccard | Java | Option 1 |
| @stephenplusplus | Node | Option 2 |
| @callmehiphop | Node | Option 1 |
| @dhermes | Python | Option 1 |
| @tseaver | Python | Option 1 |
| @blowmage | Ruby | Option 1 |
| @quartzmo | Ruby | Option 1 |

Option 1 status:
- [ ] Go (@okdave): `<link to issue here>`
- [ ] Java (@aozarov): `<link to issue here>`
- [ ] Node (@stephenplusplus): `<link to issue here>`
- [ ] Python (@dhermes): `<link to issue here>`
- [ ] Ruby (@blowmage): `<link to issue here>`

**Comment by callmehiphop** [comment]
I like this, especially because @stephenplusplus is the only one who picked Option 2. Way to be difficult Stephen!
