### ISSUE TITLE
Links to Pub/Sub API docs are 404

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/google-cloud-common#190]
_From @jdpedrie on September 23, 2016 14:39_

Hey fellas,

We ran into this issue earlier this week and I thought I'd check the other language libraries as well. It looks like Google recently moved the documentation location for PubSub, so a quick glance at your documentation shows the API documentation links under "More Information" are now 404.

Quick fix is:

```
Before: https://cloud.google.com/pubsub/reference/rest
After: https://cloud.google.com/pubsub/docs/reference/rest
```
- [x] Node (@stephenplusplus, @callmehiphop)
- [x] Ruby (@quartzmo, @blowmage)
- [x] Python (@tseaver, @dhermes, @daspecster)

_Copied from original issue: GoogleCloudPlatform/google-cloud-node#1609_

**Comment by stephenplusplus** [comment]
Thanks!

**Comment by stephenplusplus** [comment]
_From @jdpedrie on September 23, 2016 14:41_

/cc @quartzmo @blowmage looks like Ruby has the same issue.

**Comment by stephenplusplus** [comment]
_From @callmehiphop on September 23, 2016 14:51_

Might want to just open an issue on gcloud-common

**Comment by stephenplusplus** [comment]
I'll move it.

**Comment by quartzmo** [comment]
@jdpedrie Thanks for letting us know!

**Comment by daspecster** [comment]
Ditto! Thanks!
https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2398

**Comment by tseaver** [comment]
Who gets the beating for not adding the redirect?

**Comment by quartzmo** [comment]
Please note that the change is true for `/rpc` API docs as well as `/rest`:

```
Before: https://cloud.google.com/pubsub/reference/rpc
After: https://cloud.google.com/pubsub/docs/reference/rpc
```
