### ISSUE TITLE
Custom Endpoint Environment Variables

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/google-cloud-common#193]
RE: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1630
RE: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1655

In Node, we're going to support env vars that will override where we point our API requests for all of the services we support. They'll be in the format of

```
GOOGLE_CLOUD_{SERVICE}_ENDPOINT
```

i.e.
- `GOOGLE_CLOUD_BIGQUERY_ENDPOINT`
- `GOOGLE_CLOUD_BIGTABLE_ENDPOINT`
- `GOOGLE_CLOUD_COMPUTE_ENGINE_ENDPOINT` // GCE_ENDPOINT?
- `GOOGLE_CLOUD_DATASTORE_ENDPOINT`
- `GOOGLE_CLOUD_DNS_ENDPOINT`
- `GOOGLE_CLOUD_LANGUAGE_ENDPOINT`
- `GOOGLE_CLOUD_LOGGING_ENDPOINT`
- `GOOGLE_CLOUD_PREDICTION_ENDPOINT`
- `GOOGLE_CLOUD_PUBSUB_ENDPOINT`
- `GOOGLE_CLOUD_RESOURCE_MANAGER_ENDPOINT`
- `GOOGLE_CLOUD_SPEECH_ENDPOINT`
- `GOOGLE_CLOUD_STORAGE_ENDPOINT`
- `GOOGLE_CLOUD_TRANSLATE_ENDPOINT`
- `GOOGLE_CLOUD_VISION_ENDPOINT`

@jgeewax @omaray -- is this format correct?

**Comment by dhermes** [comment]
The env. vars that the 3 existing emulators are

```
DATASTORE_EMULATOR_HOST
   PUBSUB_EMULATOR_HOST
 BIGTABLE_EMULATOR_HOST
```

Are you asking users to provide an additional env. var. different from the one provided by

```
gcloud beta emulators {SERVICE} env-init
```

**Comment by stephenplusplus** [comment]
No, those should still be supported. This is a separate effort to allow a user to override any service's endpoint.

For Node right now, that means:

- `GOOGLE_CLOUD_BIGQUERY_ENDPOINT`
- `GOOGLE_CLOUD_BIGTABLE_ENDPOINT`
- `GOOGLE_CLOUD_COMPUTE_ENGINE_ENDPOINT`
- `GOOGLE_CLOUD_DATASTORE_ENDPOINT`
- `GOOGLE_CLOUD_DNS_ENDPOINT`
- `GOOGLE_CLOUD_LANGUAGE_ENDPOINT`
- `GOOGLE_CLOUD_LOGGING_ENDPOINT`
- `GOOGLE_CLOUD_PREDICTION_ENDPOINT`
- `GOOGLE_CLOUD_PUBSUB_ENDPOINT`
- `GOOGLE_CLOUD_RESOURCE_MANAGER_ENDPOINT`
- `GOOGLE_CLOUD_SPEECH_ENDPOINT`
- `GOOGLE_CLOUD_STORAGE_ENDPOINT`
- `GOOGLE_CLOUD_TRANSLATE_ENDPOINT`
- `GOOGLE_CLOUD_VISION_ENDPOINT`

For consistency, I think we should support this format for all APIs, then check for the known official emulator vars, then use the default remote endpoint.
