### ISSUE TITLE
Auth on compute engine is a bit misleading

### ISSUE THREAD

**Issue by jgeewax** [googleapis/google-cloud-common#20]
Referring to https://github.com/GoogleCloudPlatform/gcloud-common/blob/master/authorization/readme.md

We handle authentication -- not necessarily authorization without you specifically asking.

When you create a new machine on GCE, you need to choose "advanced" and tell us what scopes to give the VM. We need to be careful about this... :(

**Comment by stephenplusplus** [comment]
How do we fix this?

```diff
- # Authorization
+ # Authentication

- If you are running this client on Google Compute Engine, we handle authorization for you with no configuration.
+ If you are running this client on Google Compute Engine, we handle authentication for you with no configuration.
```

**Comment by jgeewax** [comment]
We also should include the whole "here's how you'd set up the right scopes when creating a new VM !" (with pretty screen shots... they're under "advanced" in the GCE new VM screen)

**Comment by stephenplusplus** [comment]
We do link to the official guide on that: https://cloud.google.com/compute/docs/authentication#using.

If there was a good guide on setting up a service key, I would link to that too instead of duplicate instructions. We can see in #21 how that worked out...
