### ISSUE TITLE
location of .json

### ISSUE THREAD

**Issue by SueDunome** [googleapis/google-cloud-common#211]
gcloud-common/authentication/readme.md

So where do you put the .json file after downloading...?

**Comment by jdpedrie** [comment]
It generally doesn't matter too much, though for security purposes you should **never** place it inside your web root, or anywhere where it is publicly accessibly.

Which google cloud language library are you trying to implement? The way you would provide credentials to the library varies by language. If you tell me which language you're using, I can give you more specific information on how to get started.
