### ISSUE TITLE
Create our standard labels for the gcloud-common repo

### ISSUE THREAD

**Issue by bjwatson** [googleapis/google-cloud-common#220]
This is a repo that our language-specific manual layers depend upon. We need the standard labels defined here, too.

**Comment by danoscarmike** [comment]
Adding or updating the following labels:

- [ ] type: bug (#db4437)
- [ ] type: process (#c5def5)
- [ ] type: cleanup (#c5def5)
- [ ] type: feature request (#c5def5)
- [ ] type: question (#c5def5)
- [ ] priority: p0 (#b60205)
- [ ] priority: p1 (#ffa03e)
- [ ] priority: p2 (#fef2c0)

**Comment by danoscarmike** [comment]
All done, 3+ years later 😄
