### ISSUE TITLE
Add generic auth document

### ISSUE THREAD

**Issue by dhermes** [googleapis/google-cloud-common#25]
See https://github.com/GoogleCloudPlatform/gcloud-python/pull/1084#issuecomment-134669192

/cc @jgeewax

**Comment by stephenplusplus** [comment]
Isn't this what we already have? https://github.com/GoogleCloudPlatform/gcloud-common/tree/master/authorization

**Comment by stephenplusplus** [comment]
Oh right, we don't have how to set the env var or `gcloud auth login`. We should be able to fit that into the current authorization guide -- or make a new one on authentication? My head still spins a bit on the difference between the terms.

**Comment by dhermes** [comment]
- Authorization: Provide verified access to a resource
- Authentication: Prove identity

**Comment by stephenplusplus** [comment]
Could you lead the charge on the new / modified document, likely addressing [authentication vs authorization](https://github.com/GoogleCloudPlatform/gcloud-node/pull/861#issuecomment-140199625) at the same time?

**Comment by dhermes** [comment]
Sure thing.
