### ISSUE TITLE
Use new urls for authentication

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-cloud-common#260]
Across all languages, we need to update the urls used for OAuth token access.  

- [x] https://github.com/google/google-auth-library-java/issues/173
- [x] https://github.com/google/google-auth-library-nodejs/issues/444
- [x] https://github.com/google/google-auth-library-ruby/issues/155
- [x] https://github.com/google/google-auth-library-php/issues/205
- [x] https://github.com/GoogleCloudPlatform/google-auth-library-python/issues/281
- [x] https://github.com/golang/oauth2/issues/310
- [x] https://github.com/google/google-api-dotnet-client/issues/1269
- [x] https://github.com/google/google-api-java-client/issues/1144

The releases with this change are tracked here:
- [x] java - https://github.com/googleapis/google-api-java-client/releases/tag/1.25.0, https://github.com/googleapis/google-auth-library-java/releases/tag/v0.11.0
- [x] nodejs - https://www.npmjs.com/package/google-auth-library/v/2.0.0
- [x] ruby - https://rubygems.org/gems/googleauth/versions/0.6.5
- [x] php - https://github.com/googleapis/google-auth-library-php/releases/tag/v1.3.3
- [x] python - https://github.com/GoogleCloudPlatform/google-auth-library-python/releases/tag/v1.5.1
- [x] golang - 
- [x] dotnet - https://github.com/googleapis/google-api-dotnet-client/releases/tag/v1.35.2

The following specific library changes are required:

### OAuth 2.0 Authorization Grant Flow (aka 3LO)

For clients using this flow, change (and test):
- https://accounts.google.com/o/oauth2/token -> https://oauth2.googleapis.com/token
- https://accounts.google.com/o/oauth2/revoke -> https://oauth2.googleapis.com/revoke
- https://accounts.google.com/o/oauth2/tokeninfo -> https://oauth2.googleapis.com/tokeninfo
- *DO NOT* change https://accounts.google.com/o/oauth2/auth

If the client pulls the data from the client json object, that will be updated on the server side for newly created clients and no changes to the client libraries are required.

### OAuth 2.0 Assertion Flow (aka OAuth 2.0 Service Account Flow, aka “Google Credentials Auth”)

For clients using these flows, change:
- https://accounts.google.com/o/oauth2/token -> https://oauth2.googleapis.com/token
- The “audience” of the token from https://accounts.google.com/o/oauth2/token ->  https://oauth2.googleapis.com/token

### JWT Bearer

No changes should be required for JWT Bearer authentication

### OIDC Identity Tokens

There are two options.  If possible, the preferred option in this case is to:
- Change https://accounts.google.com/o/oauth2/token ->  https://oauth2.googleapis.com/token
- Change audience verification from “accounts.google.com” to [“accounts.google.com”, “https://accounts.google.com”]
- *DO NOT* Change https://www.googleapis.com/oauth2/v1/certs

If this is too risky in a particular client library, then the change should be:
- https://accounts.google.com/o/oauth2/token -> https://www.googleapis.com/oauth2/v3/token
- *DO NOT* Change https://www.googleapis.com/oauth2/v1/certs

**Comment by chrisdunelm** [comment]
Updated the C# issue into the correct repo.

**Comment by chrisdunelm** [comment]
As far as I'm aware, the canonical (external) source of OIDC URLs is: https://accounts.google.com/.well-known/openid-configuration
The token_endpoint specified there (https://www.googleapis.com/oauth2/v4/token) doesn't match the token_endpoint recommended above (https://oauth2.googleapis.com/token).
The "DO NOT Change" jwks URL doesn't quite match either. In `.well-known/openid-configuation` it is https://www.googleapis.com/oauth2/v3/certs, not https://www.googleapis.com/oauth2/v1/certs.
Do you know why there are these discrepancies?

Thanks.

**Comment by chingor13** [comment]
Java has 3-legged OAuth in the google-oauth-java-client so I opened [#203](https://github.com/google/google-oauth-java-client/issues/203) there as well. 

I don't have permissions to edit this meta-issue to update the checklist.

**Comment by JustinBeckwith** [comment]
Places where this is critical:  Python and Java: Dataproc, Dataflow, BigQuery, Bigtable, GCS

**Comment by JustinBeckwith** [comment]
Looping in @gdasher to help answer the question on OIDC urls :)

**Comment by chingor13** [comment]
Do we care about warning if the service account json is using one of the old urls?

**Comment by JustinBeckwith** [comment]
I wouldn't.  There are tons of these floating around, and the current urls will need to live forever.  The new urls only really matter in certain enterprise environments (@gdasher as details), and just telling them to download new keys is likely sufficient.

**Comment by tadast** [comment]
Thanks for a quick response @theacodes. I'll open a PR for the ruby library to fix that today (broken since 0.6.3), you might want to check the nodejs and python libraries too as I don't think the HTTP method got changed there either

**Comment by theacodes** [comment]
Python is fine, but Nodejs seems to be using GET as well.

**Comment by tadast** [comment]
https://github.com/google/google-auth-library-ruby/pull/157

**Comment by theacodes** [comment]
@chrisdunelm 

> As far as I'm aware, the canonical (external) source of OIDC URLs is: https://accounts.google.com/.well-known/openid-configuration
The token_endpoint specified there (https://www.googleapis.com/oauth2/v4/token) doesn't match the token_endpoint recommended above (https://oauth2.googleapis.com/token).
The "DO NOT Change" jwks URL doesn't quite match either. In .well-known/openid-configuation it is https://www.googleapis.com/oauth2/v3/certs, not https://www.googleapis.com/oauth2/v1/certs.
Do you know why there are these discrepancies?


We should prefer what's specified in the file over what's specified by the authorization server. We're also sort of breaking the rules here by saying if it's *not* specified we should prefer these new URLs.

**Comment by gdasher** [comment]
We will update the .well-known and associated documentation in the nearish future.  The urls I provided are correct and are going to be the future authoritative urls for sure.

**Comment by theacodes** [comment]
@JustinBeckwith Revocation isn't part of the RFC, but looking at the Token Endpoint section of the RFC https://tools.ietf.org/html/rfc6749#section-3.2 POST must be supported, so it's pretty safe to use that.

**Comment by chrisdunelm** [comment]
C# code change done. Will be released on 2018-09-13

**Comment by JustinBeckwith** [comment]
Thanks folks!  Please add a link in the bug description above to the release that contains this fix.  Just trying to keep the books straight :)

@chrisdunelm @chingor13 @tmatsuo @jadekler @theacodes @TheRoyalTnetennba

**Comment by crwilcox** [comment]
Node.js: https://github.com/googleapis/google-auth-library-nodejs/releases/tag/v2.0.0
Python: https://github.com/GoogleCloudPlatform/google-auth-library-python/releases/tag/v1.5.1

**Comment by chingor13** [comment]
Java:
* https://github.com/googleapis/google-api-java-client/releases/tag/1.25.0
* https://github.com/googleapis/google-auth-library-java/releases/tag/v0.11.0

**Comment by tmatsuo** [comment]
PHP: https://github.com/googleapis/google-auth-library-php/releases/tag/v1.3.3

**Comment by jskeet** [comment]
.NET: https://github.com/googleapis/google-api-dotnet-client/releases/tag/v1.35.2

**Comment by shinfan** [comment]
Go is completed: https://github.com/golang/oauth2/issues/310

It seems like all languages are completed. Shall we close this parent issue? @broady @JustinBeckwith 

FYI @wora

**Comment by jadekler** [comment]
We need to re-pin and release, so the parent issue should stay open a tiny bit more. But also, it'd be good to let this bake for a week or two, since we didn't get to do a lot of in-depth testing before it was submitted.

**Comment by jadekler** [comment]
Tracked in https://github.com/googleapis/google-cloud-go/issues/1333.

**Comment by JustinBeckwith** [comment]
This is done 🙌
