### ISSUE TITLE
Dead links for Go SDK docs

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-cloud-common#270]
I noticed that if I go to any of the library pages on the googleapis.github.io site, for example https://googleapis.github.io/google-cloud-java/google-cloud-clients/index.html, and I choose "Go", I get a 404.

**Comment by jskeet** [comment]
I suspect it depends on the language. For C#, I need to edit https://github.com/googleapis/google-cloud-dotnet/blob/gh-pages/index.html - which I notice I haven't updated for our org change at all...

**Comment by jdpedrie** [comment]
@JustinBeckwith for java, you can edit them [here](https://github.com/googleapis/google-cloud-java/blob/gh-pages/google-cloud-clients/index.html#L24-L73).

**Comment by JustinBeckwith** [comment]
If the change is over in the Java repo, I'm swinging this over to Jeff :)

**Comment by blowmage** [comment]
I assume it was because the repo used to be at googleapis/google-cloud-go (or GoogleCloudPlatform/google-cloud-go before that), but it was moved. So now the links don't work. Where is the repo now?

**Comment by enocom** [comment]
https://github.com/googlecloudplatform/google-cloud-go

**Comment by blowmage** [comment]
Ah, so the repo was never moved to googleapis organization? The Ruby links are relative, so when the Ruby repo moved so did the host for the relative links.

It looks like C++ and Go are still on the old organization., so we should update the links accordingly. Are those repos planning on moving organizations eventually?

**Comment by blowmage** [comment]
Ruby has fixed these links: https://github.com/googleapis/google-cloud-ruby/commit/5f54ed9cfe4f19b100ac2de3b7ea4d6ba564993b

**Comment by jadekler** [comment]
Thanks for that @blowmage, much appreciated

**Comment by JustinBeckwith** [comment]
Yup!  Appears to work now.
