### ISSUE TITLE
Should separate APIs be separately installable?

### ISSUE THREAD

**Issue by tseaver** [googleapis/google-cloud-common#30]
This [issue](https://github.com/GoogleCloudPlatform/gcloud-python/issues/1159) came up today for `gcloud-python`, prompted largely by not being able to bring in `gcloud.bigtable` until we have a good installation / CI story for it (`gRPC` installation issues).

**Comment by stephenplusplus** [comment]
Related: https://github.com/GoogleCloudPlatform/gcloud-node/issues/91

**Comment by dhermes** [comment]
:+1: 

For discussion with those unfamiliar with the Python packaging story, here is a little background.

We could allow users to install the unbundled stuff in two ways.

**Option A**: Add optional targets / dependencies to our main project

```bash
$ pip install gcloud
$ pip install gcloud[datastore]
$ pip install gcloud[pubsub,storage]
$ pip install gcloud[all]
```

**Option B**: Separate each service-specific sub-package into its own project and it's own dedicated package on PyPI:

```bash
$ pip install gcloud-datastore  # Pulls in pip install gcloud automatically
$ pip install gcloud-pubsub gcloud-storage
$ # Not sure how pip install gcloud-all would work
```

----

In either case, we could enable it so that users could use the `gcloud` namespace / package to manage all subpackages:

```python
from gcloud import datastore
from gcloud.storage.bucket import Bucket
import gcloud.pubsub
```

or we could change the philosophy and have a separate package for every service (i.e. no parent namespace):

```python
import gcloud_datastore as datastore 
from gcloud_storage.bucket import Bucket
import gcloud_pubsub
```

----

I assume there are equivalent notions in the `gem`, `npm` and `maven`. Anyone care to share?

**Comment by jgeewax** [comment]
I like option A, with one tweak: I think it'd be better to have the shared stuff be `gcloud[core]`, and then `gcloud` would be the same as what we're calling `gcloud[all]` in Option A.

Some examples...

Goal|Command
---|---
Everything at latest|`pip install gcloud`
Just datastore|`pip install gcloud[datastore]`
Everything + specific version of datastore|`pip install gcloud gcloud[datastore]==X` (?)

If you end up with a situation where you require different versions of `gcloud[core]`... I'm not sure what we do here, maybe that's a place for virtualenv to get involved.

---

> In either case, we could enable it so that users could use the gcloud namespace / package to manage all subpackages:

I completely agree with this. `gcloud_datastore` bums me out. :+1: to `gcloud.datastore`.

**Comment by dhermes** [comment]
@jgeewax That's not possible `pip install foo` is a base and `pip install foo[bar]` adds on `bar` extras to the base `foo` install.

**Comment by jgeewax** [comment]
No way at all? That makes me sad... The "common case" (which is "I just want the stuff") would be ... trickier.

What about swapping brackets for dashes? And using some aliasing magic?

Goal|Command
---|---
Everything at latest|`pip install gcloud`
Just datastore|`pip install gcloud-datastore`
Everything + specific version of datastore|`pip install gcloud gcloud-datastore==X` (?)

Is that doable while still keeping the `gcloud.datastore` import syntax? Or will we be forced to use `gcloud_datastore` in imports?

**Comment by dhermes** [comment]
Yes the `gcloud.datastore` import syntax can be supported from separate PyPI packages by using a namespace package (https://www.python.org/dev/peps/pep-0420/).

**Comment by tseaver** [comment]
If we make a bare `gcloud` install everything, then:
- We miss some of the point of the split (e.g., reducing complex dependencies for stuff like `bigtable` -> `gRPC`).
- We would need to move all the "core" code into a separate package (e.g., `gcloud-core`) on which all the API packages would depend (no cycles).
