### ISSUE TITLE
New Google Cloud Platform icon for docs site

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/google-cloud-common#38]
_From @ryanseys on October 12, 2015 21:28_

I noticed [your site](https://googlecloudplatform.github.io/gcloud-node/#/) is still using the old Google logo in the header. Below I have attached the new logo to replace it.

![new-gcp-logo](https://cloud.githubusercontent.com/assets/163873/10439205/3b2b1aee-70ed-11e5-9e0d-d3a8e6a924d9.png)

_Copied from original issue: GoogleCloudPlatform/gcloud-node#908_

**Comment by stephenplusplus** [comment]
_From @dhermes on October 13, 2015 0:35_

Ohhhh fancy

**Comment by stephenplusplus** [comment]
I think we need this in higher quality and SVG. Know of any asset stashes?

**Comment by ryanseys** [comment]
Let me see what I can do.

**Comment by stephenplusplus** [comment]
Thanks!

**Comment by ryanseys** [comment]
Found some! No svgs but let me know if these are good :smile: 

Color:
![google-dev-logo](https://cloud.githubusercontent.com/assets/163873/11508340/1f19879a-980d-11e5-9a51-51b06cb2dd3e.png)

White:
![googl-dev-logo-white](https://cloud.githubusercontent.com/assets/163873/11508369/493ce0bc-980d-11e5-9d53-c91aec7aea0a.png)

Black:
![google-dev-logo-blk](https://cloud.githubusercontent.com/assets/163873/11508371/4b357c76-980d-11e5-95d4-2ffd59653931.png)

**Comment by stephenplusplus** [comment]
I did some Photoshopping to get the Black to be white, and ended up here:

<img width="592" alt="screen shot 2015-12-01 at 12 41 15 pm" src="https://cloud.githubusercontent.com/assets/723048/11508850/db710420-9828-11e5-8d83-a6520e05d5e9.png">
<img width="539" alt="screen shot 2015-12-01 at 12 41 06 pm" src="https://cloud.githubusercontent.com/assets/723048/11508851/db72c314-9828-11e5-935d-d48dc1f75586.png">

@jgeewax is this alright?
