### ISSUE TITLE
Embed the bug filing form in our docs?

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/google-cloud-common#39]
_From @jgeewax on October 6, 2015 15:52_

Looks like the GH guys make this pretty easy, where we could just fire off an AJAX request for issues...

This might be something to look into more ... 

https://developer.github.com/v3/issues/#create-an-issue
- screenshot

<img width="455" alt="screen shot 2015-10-06 at 10 39 32 am" src="https://cloud.githubusercontent.com/assets/112928/10314020/964b7ff8-6c20-11e5-8b72-73e995c643eb.png">

don't know if we can make it that pretty... but... :)

_Copied from original issue: GoogleCloudPlatform/gcloud-node#906_

**Comment by stephenplusplus** [comment]
This could be cool, but I think it only works for repo owners, probably after going through an oauth GH signin process:

> Any user with pull access to a repository can create an issue.

**Comment by stephenplusplus** [comment]
_From @jgeewax on October 6, 2015 16:40_

I think most users should have pull access -- but not push access (ie,
editing requires push access
https://developer.github.com/v3/issues/#edit-an-issue)

**Comment by stephenplusplus** [comment]
_From @callmehiphop on October 6, 2015 16:52_

I like it! 

Should we make a repo for docs? I only ask because I know python and ruby (and maybe php?) are probably going to want this functionality as well, not to mention we may eventually move to a templated site for docs.

**Comment by stephenplusplus** [comment]
_From @jgeewax on October 6, 2015 16:55_

I think the plan is:

- put most work into gcloud-node docs angular app
- get other repos spitting out JSON consumable by that app
- split gcloud-node app into a separate repository
- make the "update docs" task clone that repository, and ship it (+ the
JSON generated) to gh-pages

seem reasonable?

**Comment by stephenplusplus** [comment]
_From @callmehiphop on October 6, 2015 17:1_

yep!

**Comment by jgeewax** [comment]
Interesting read related to this issue: http://archetyped.com/know/guided-github-reports/

**Comment by callmehiphop** [comment]
Nice, I think I prefer that approach
