### ISSUE TITLE
Cloud Bigtable API updates coming in Late Jan

### ISSUE THREAD

**Issue by carterpage** [googleapis/google-cloud-common#45]
Heads up, Cloud Bigtable will be making updates to the API early next year. It will have almost no impact on the data API, minor impact on the Admin API, and significant changes to cluster API.

Basic idea is that clusters will now be part of a higher level concept called an instance.

Going from this:

project -> cluster

To:

project -> instance -> cluster

More details to come once finalized.

@maxluebbe

**Comment by dhermes** [comment]
Thanks for the heads up.
