### ISSUE TITLE
Support for "gcloud beta emulators pubsub"

### ISSUE THREAD

**Issue by hbchai** [googleapis/google-cloud-common#48]
The Pub/Sub emulator can be run, and environment variables exported, with:

```
gcloud beta emulators pubsub start &
$(gcloud beta emulators pubsub env-init)
```

The pubsub libraries should detect this environment variable and connect to the emulator when it is available, similar to how it works for the Datastore emulator. **Please ensure that the default application credentials are NOT passed on to the emulator.**
- [x] Python (https://github.com/GoogleCloudPlatform/gcloud-python/pull/1344)
- [ ] Java (https://github.com/GoogleCloudPlatform/gcloud-java/issues/998)
- [x] Golang (https://github.com/GoogleCloudPlatform/gcloud-golang/issues/206)
- [x] Node (https://github.com/GoogleCloudPlatform/gcloud-node/issues/1046, https://github.com/GoogleCloudPlatform/gcloud-node/issues/1125)
- [x] Ruby (GoogleCloudPlatform/gcloud-ruby#491)

Note: Currently gcloud exports `PUBSUB_HOSTPORT`. I think we're probably going to change this to simply ~~`PUBSUB_HOST`~~ `PUBSUB_EMULATOR_HOST` for consistency; changes targeting this issue should look for ~~`PUBSUB_HOST`~~ `PUBSUB_EMULATOR_HOST`. The value of this variable with be something like "localhost:1234" - note in particular no "http://" scheme prefix.

**Comment by hbchai** [comment]
See https://github.com/GoogleCloudPlatform/gcloud-common-private/issues/4

**Comment by dhermes** [comment]
FYI @hbchai we (`gcloud-python`) put every env. var we use in
https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/gcloud/environment_vars.py
to keep track of what is on and what is off.

**Comment by dhermes** [comment]
@hbchai Should we implement `PUBSUB_HOSTPORT` in the meanwhile and wait to hear back from you when there is a change? With the (latest?) version of `gcloud` (91.0.1) it seems the init command just sets the env var:

```bash
$ gcloud beta emulators pubsub env-init
export PUBSUB_HOSTPORT=localhost:8506
```

**Comment by hbchai** [comment]
@dhermes I just submitted the change to `PUBSUB_HOST`, so it should be available with the next release of gcloud. I think we can just implement it for `PUBSUB_HOST` to keep things simple.

**Comment by hbchai** [comment]
@dhermes I just discussed a couple of things with the datastore emulator developer; we may want to change the environment variable naming scheme a bit. For example, using PUBSUB_EMULATOR_HOST, with a value that does not include the URL scheme (no "http://" prefix, e.g. simply "localhost:1234"). That would mean that gcloud-python would have to construct the base URL.

**Comment by dhermes** [comment]
Just let us know once it's finalized and we're happy to support whatever you like

**Comment by dhermes** [comment]
@hbchai I am trying to modify our system tests to run with the emulator as in https://github.com/GoogleCloudPlatform/gcloud-python/pull/1369 but all my requests are failing and the error message is empty (with status code 400).

The URI used is

```
http://localhost:8189/v1/projects/GCLOUD-DEFAULT-PROJECT/topics/a-new-topic
http://localhost:8189/v1/projects/GCLOUD-DEFAULT-PROJECT/topics/new1452289655691
http://localhost:8189/v1/projects/GCLOUD-DEFAULT-PROJECT/topics/subscribe-me
```

where `localhost:8189`

```
$ gcloud beta emulators pubsub env-init
export PUBSUB_HOSTPORT=localhost:8189
```

**Comment by hbchai** [comment]
What happens when you try to access one of those URLs in a browser?

**Comment by dhermes** [comment]
Well the browser does a `GET` request but these failures were for inserting a new topic (via `PUT`).

```python
>>> import httplib2
>>> http = httplib2.Http()
>>> URI = ('http://localhost:8189/v1/projects/'
...        'GCLOUD-DEFAULT-PROJECT/topics/subscribe-me')
>>> resp, content = http.request(URI, method='PUT')
>>> resp
{'content-length': '73', 'content-type': 'application/json', 'status': '404'}
>>> content
'{"error":{"code":404, "message":"Topic not found", "status":"NOT_FOUND"}}'
>>> headers = {
...     'Accept-Encoding': 'gzip',
...     'Content-Length': '0',
...     'User-Agent': 'gcloud-python/0.8.0',
... }
>>> resp, content = http.request(URI, method='PUT', headers=headers)
>>> resp
{'content-length': '0', 'status': '400'}
>>> content
''
>>> headers['Content-Type'] = 'application/json'
>>> resp, content = http.request(URI, method='PUT',
...                              headers=headers, body='{}')
>>> resp
{'content-length': '0', 'status': '400'}
>>> content
''
>>> body = '{"name": "projects/GCLOUD-DEFAULT-PROJECT/topics/subscribe-me"}'
>>> resp, content = http.request(URI, method='PUT',
...                              headers=headers, body=body)
>>> resp
{'content-length': '0', 'status': '404'}
>>>
''
```

**Comment by hbchai** [comment]
I think this may be an issue that's resolved in the new version of the
emulator, basically that a PUT with an empty body wasn't being treated the
same as a PUT with an empty Json string (e.g. "{}").

**Comment by dhermes** [comment]
1. I made 3 PUT requests above, only one of them has an empty body. Empty body -> 400, `{}` body -> 400 and `{"name": "projects/..."}` body -> 404.
1. Is the new version released? I ran `gcloud components update` and it tells me all components are up to date. (I was worried that `gcloud beta emulators pubsub env-init` didn't have the new env. var.)

**Comment by hbchai** [comment]
Lost track of this - sorry for the late reply. Can you try again? I tried some of the python commands and they seemed to work correctly. (There might be a problem with specifying a zero content length.) BTW, the emulator will support Gzip-encoded requests as of an expected release this week.

**Comment by dhermes** [comment]
@hbchai The new version released "fixed everything". You can just run `tox -e pubsub-emulator` and our system tests all get run locally (with no internet needed).

**Comment by hbchai** [comment]
@dhermes Thanks for the confirmation!

**Comment by blowmage** [comment]
Does the emulator run the REST API? Or does it run the GRPC API?

**Comment by hbchai** [comment]
@blowmage It supports both on a single port, using HTTP version to distinguish (HTTP/1 => REST, HTTP/2 => gRPC).

**Comment by SaMnCo** [comment]
@hbchai, @dhermes probably a stupid question but is there a doc explaining how to use the gcloud-python library against the pubsub-emulator? 
I can't get my head around the configuration, and it always tries to get to the cloud API. 

Thanks in advance. If there is none, I am happy to participate it if I can get it to work in a repeatable way, which is not the case yet.

**Comment by dhermes** [comment]
Thanks a lot for the question. Have you seen https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/CONTRIBUTING.rst

**Comment by SaMnCo** [comment]
@dhermes I have now, signed up for the personal CLA & forked the repo. I'll have a look at the code that runs the unitests, I should be able to understand how to use it for in other context (namely, I want to run it in a container to have a more generic way of emulating the pubsub API). 
I'll publish my results in the format required. 
In the meantime, if you have any guidance on usage, feel free to share links. 
Thanks,

**Comment by hbchai** [comment]
@SaMnCo Maybe you can describe what you've tried. Running `gcloud beta emulators pubsub start` starts the emulator locally. Running `$(gcloud beta emulators pubsub env-init)` will export environment variables into a shell. Subsequently running a gcloud-python client in that shell will use the environment variables to connect to the running emulator. Exact details of this may change in the future, but this workflow is basically correct.

**Comment by SaMnCo** [comment]
Sure. I'm in Ubuntu 15.10, default system python 2.7.10. 

```
$ sudo pip install --upgrade gcloud
$ git clone https://github.com/GoogleCloudPlatform/gcloud-python
$ cd gcloud-python && sudo python setup.py install

```
==> At this point, I should have a working environment.

```
$ gcloud beta emulators pubsub start &
$ $(gcloud beta emulators pubsub env-init) # This seems to only export a the pubsub host
```

Now trying to run the pubsub client: 

```
$ python
Python 2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from gcloud import pubsub
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gcloud-0.9.0-py2.7.egg/gcloud/pubsub/__init__.py", line 26, in <module>
    from gcloud.pubsub.client import Client
  File "/usr/local/lib/python2.7/dist-packages/gcloud-0.9.0-py2.7.egg/gcloud/pubsub/client.py", line 18, in <module>
    from gcloud.client import JSONClient
  File "/usr/local/lib/python2.7/dist-packages/gcloud-0.9.0-py2.7.egg/gcloud/client.py", line 19, in <module>
    from gcloud._helpers import _determine_default_project
  File "/usr/local/lib/python2.7/dist-packages/gcloud-0.9.0-py2.7.egg/gcloud/_helpers.py", line 26, in <module>
    from google.protobuf import timestamp_pb2
ImportError: cannot import name timestamp_pb2
```
This same error happens for each and every script in the gcloud-python tree. 

In general, the use case I have is: 
* I want to run the pubsub emulator in a Docker container (that part is done)
* I understand that if I run my container with ```docker run -itd --name pubsub-emulator -p 8042:8042 samnco/pubsub:2016.01.22``` on host "foobar", then from a developer machine, running ```export PUBSUB_EMULATOR_HOST=foobar:8042``` should be the only command required to access the emulator from python code right?
* This makes me wonder about authentication in this context, and how it will be handled. 

We can move this to the actual gcloud-python I guess. Let me know your thougths.

**Comment by hbchai** [comment]
I'm not sure what's going on with the Python import error there. @dhermes ?

When you start the emulator in the container, you'll probably have to specify the host explicitly; the emulator binds to localhost by default and cannot be accessed remotely. You can do this by specifying the `--host-port` flag to the emulator start command.

The emulator is simplistic and does not perform authentication. Requests to it should not have auth attached.

**Comment by dhermes** [comment]
@SaMnCo let's move this over to the `gcloud-python` issue I referred to you in

**Comment by SaMnCo** [comment]
@dhermes thanks, will follow up on #1436. I had spotted it as well as a potential match for my issue. 

@hbchai, I think the container is ok even if I can't test. I can see the log trace. The Dockerfile is [here](https://github.com/SaMnCo/docker-pubsub-emulator) and it's also on the docker registry if that's of any use.

**Comment by hbchai** [comment]
@SaMnCo - Very cool with the docker container! It would be interesting to hear how you are using this and whether it's helpful for your testing. It's important for us to hear that emulators are useful for developers.

**Comment by SaMnCo** [comment]
@hbchai Well, I am working on the infrastructure side for an app that will run on GCE for stateful side, and GKE for the stateless part. There is a pubsub service requirement in it so gcloud pubsub was a natural choice. But then the question was how to test it offline, in an easy and replicable way. 
While asking all devs to install gcloud is an option, they are more familiar with containers, and having an ops-managed container makes a lot more sense, so it keeps in line with what they are using in staging and prod. 
Now hopefully we can get to a point where I can give them a docker-compose.yml or a k8s model to deploy locally, and they won't see any difference with the real environment. 

If we use the datastore, I'll do the same and provide them with a container as well. I guess, from my perspective, the ability to emulate any cloud service locally means I can work on my laptop offline, and that helps me. 

Hope it helps :)

**Comment by dhermes** [comment]
@hbchai Our system tests have started failing with the emulator. First `gcloud beta emulators pubsub start` failed because the underlying script isn't executable. After fixing it:

```
chmod +x ${HOME}/google-cloud-sdk/platform/pubsub-emulator/bin/cloud-pubsub-fake
```

I'm getting 400 Invalid subscriptions name for

```
http://localhost:8541/v1/projects/{PROJECT}/subscriptions/test-sub-iam-policy-sub-1461361234772:getIamPolicy
```

and 400 Invalid topics name for

```
http://localhost:8541/v1/projects/{PROJECT}/topics/test-topic-iam-policy-topic-1461361234826:getIamPolicy
```

(These paths are "identical" to passing system tests we execute against the live API.)

/cc @tseaver 

----

My `gcloud` install:

```
$ gcloud --version
Google Cloud SDK 106.0.0

alpha 2016.01.12
app-engine-java 1.9.34
app-engine-python 1.9.35
app-engine-python-extras 1.9.21
beta 2016.01.12
bq 2.0.24
bq-nix 2.0.24
core 2016.04.14
core-nix 2016.03.28
gcd-emulator v1beta3-1.0.0
gcloud 
gsutil 4.19
gsutil-nix 4.18
pubsub-emulator 2016.02.22
```

**Comment by hbchai** [comment]
Thanks for reporting this. No changes have been made to the emulator logic
regarding names recently - has the test changed?

The name validation attempts to follow the spec:
https://github.com/googleapis/googleapis/blob/master/google/pubsub/v1/pubsub.proto#L257
 Note that ":" is not an allowed character. However, it appears that we're
currently rejecting other allowed characters ("~", "+", "%") which should
be fixed.

It may be the case that the actual system accepts other inputs, but that
could change at any time.

**Comment by dhermes** [comment]
> No changes have been made to the emulator logic regarding names recently - has the test changed?

Yes, those two test cases are new. But as I said, they do work just fine with the live API server.

> Note that ":" is not an allowed character.

Am I missing something? AFAICT the URIs above only contain alphanumeric and `-`.

**Comment by hbchai** [comment]
It's the `:getIamPolicy` suffix to both. I'm assuming by `{PROJECT}` you would have substituted some other value; braces are also not allowed by the spec, though the code might be erroneously permissive with that now.

**Comment by dhermes** [comment]
I need to get my eyes checked; I saw a period (`.`) not a colon (`:`)! Yes `{PROJECT}` is a placeholder, `gcloud` uses my local default project. According to the docs for both methods ([subs][1] and [topics][2]) the `:` should be in the URI. This doesn't contradict the [sub name rule][3] in the proto, though the `getIamPolicy` methods don't exist in the `Subscriber` or `Publisher` proto services. From the doc, see the URI / request templates are:

```
GET https://pubsub.googleapis.com/v1/{resource=projects/*/subscriptions/*}:getIamPolicy
GET https://pubsub.googleapis.com/v1/{resource=projects/*/topics/*}:getIamPolicy
```

[1]: https://cloud.google.com/pubsub/reference/rest/v1/projects.subscriptions/getIamPolicy
[2]: https://cloud.google.com/pubsub/reference/rest/v1/projects.topics/getIamPolicy
[3]: https://github.com/googleapis/googleapis/blob/48063b2af6dc55fd6a148b359538b56aa5c5c043/google/pubsub/v1/pubsub.proto#L257

**Comment by hbchai** [comment]
Oh right. Those methods aren't implemented in the emulator; currently only the methods in the v1 proto. I believe the IAM-related methods cut across all APIs, maybe that's why. Is support for these methods important for you?

**Comment by dhermes** [comment]
I just filed https://github.com/GoogleCloudPlatform/gcloud-python/pull/1748 to have the system tests ignore those test cases when run in the emulator.

I can't really say if these methods are important for **me**, though it's unclear why you wouldn't want your emulator to emulate the API. @jgeewax WDYT?

**Comment by dhermes** [comment]
@hbchai I discovered another difference between the live API and emulator. Is there a more appropriate place to file bugs?

----

The summary (I don't want to distract from the above) is as follows:

The [docs][1] say that when a topic is deleted the 

> Existing subscriptions to this topic are not deleted, but their topic field is set to `_deleted-topic_`

but the emulator does not do this, which causes our unit test [`test_fetch_delete_subscription_w_deleted_topic`][2] to fail.

[1]: https://cloud.google.com/pubsub/reference/rest/v1/projects.topics/delete
[2]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/bd89bfe9bfc84b2555e4f20ac97f172aace16536/system_tests/pubsub.py#L211

**Comment by hbchai** [comment]
@dhermes The pubsub emulator doesn't implement any authentication or authorization now, as a simplification. It might still be possible to implement the IAM methods (apparently [defined here](https://github.com/googleapis/googleapis/blob/master/google/iam/v1/iam_policy.proto)); we didn't think it would be common to call these on the emulator. I agree that we'll have to implement them at some point.

Second bug - good catch. For some reason that behavior of delete didn't catch my eye before.

The emulator code will eventually make it to github at which point we'll have a convenient place to report bugs, but we still need to do some internal cleanups before that happens. For now, bugs can be reported here; please continue to cc me.

**Comment by rdsubhas** [comment]
@hbchai Looks like Java support for this has been merged:

- https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1317
- https://github.com/GoogleCloudPlatform/google-cloud-java/issues/998

We have been following this issue eagerly, is this issue considered closed now? 😄

**Comment by hbchai** [comment]
Cloud SDK version 143.0.1 fixes some name validation issues mentioned in a [comment above](https://github.com/GoogleCloudPlatform/gcloud-common/issues/48#issuecomment-213752386).
