### ISSUE TITLE
Improve CONTRIBUTING.md ?

### ISSUE THREAD

**Issue by callmehiphop** [googleapis/google-cloud-common#50]
_From @jgeewax on January 19, 2016 11:13_

PM2 seems to have a really nice guide to contributing. Maybe we can take some guidance from them?

https://github.com/Unitech/PM2/blob/master/CONTRIBUTING.md

_Copied from original issue: GoogleCloudPlatform/gcloud-node#1072_

**Comment by stephenplusplus** [comment]
I think the ideal structure is...

- Let the common contributing file say the generic stuff (how to search issues, open an issue, etc)

- Let each repo's unique contributing file say project-specific stuff (how to run tests, set env vars, etc)

And I think that's how we're already doing it. So the only thing left to do is:

1. Improve the common contributing file, if necessary?
2. Link from each project's contributing file to the common one

**Comment by callmehiphop** [comment]
_From @stephenplusplus on January 19, 2016 11:18_

It's kinda tricky, cause we have https://github.com/GoogleCloudPlatform/gcloud-common/tree/master/contributing for the generic "How to open an issue", but someone looking at our CONTRIBUTING.md file (as opposed to https://googlecloudplatform.github.io/gcloud-node/#/contributing won't see that).

Maybe we should just have a link back to the gcloud-common file at the top of ours?
