### ISSUE TITLE
Make master a protected branch in all repos

### ISSUE THREAD

**Issue by dhermes** [googleapis/google-cloud-common#53]
See https://help.github.com/articles/configuring-protected-branches/
- [ ] `gcloud-golang`
- [ ] `gcloud-java`
- [x] `gcloud-node`
- [x] `gcloud-php`
- [x] `gcloud-python`
- [x] `gcloud-ruby`

(@stephenplusplus was here)

**Comment by blowmage** [comment]
The gcloud-ruby master branch is now protected.
