### ISSUE TITLE
Add your credentials to this issue?

### ISSUE THREAD

**Issue by jgeewax** [googleapis/google-cloud-common#66]
Can everyone comment back with your:
- gmail address
- project ID for development
- project ID for your project's tests
- service account email for development
- service account email for your project's tests

?

This is for whitelisting, because it's getting really troublesome to dig through old e-mails for this stuff....

/cc @stephenplusplus @callmehiphop @dhermes @tseaver @blowmage @quartzmo @dwsupplee @aozarov @mziccard @ajkannan @okdave

**Comment by blowmage** [comment]
Developer Gmail (gcloud-ruby):
* Mike - mike@blowmage.com
* Chris - quartzmo@gmail.com

Project ID (development): nodal-almanac-725
Project ID (test): helical-zone-771

Service Account Email (development): 324770174224-rhu780vlhjb4bsohfoqvsjik1tj0d70f@developer.gserviceaccount.com
Service Account Email (test): 542339357638-cr0dserr2evg7sv1meghqeu703274f3h@developer.gserviceaccount.com

**Comment by dwsupplee** [comment]
dwsupplee@gmail.com

Project ID for dev - phil-connors
Service account email for dev - 344567941694-tn3lgp87ff3jj7o8bapivj5a1pathgip@developer.gserviceaccount.com

Testing accounts need to be created.

**Comment by stephenplusplus** [comment]
#### Me

- sawchuk@gmail.com
- nth-circlet-705
- 288560394597-j1gpp1u715vn62a9vktblj6h1gs7iu10@developer.gserviceaccount.com

#### gcloud-node System Tests

- long-door-651
- 1046198160504-pvpfitu54aug5bje4fnaub2r8vv0siu5@developer.gserviceaccount.com

**Comment by callmehiphop** [comment]
callmehiphop@gmail.com
boreal-physics-911
806989004347-eor9d63e8ad1otbud07j57dnf2g1058l@developer.gserviceaccount.com

**Comment by dhermes** [comment]
#### Me

- daniel.j.hermes@gmail.com
- `omega-moonlight-697`
- service-account-again@omega-moonlight-697.iam.gserviceaccount.com

#### `gcloud-python` System Tests

- `precise-truck-742`
- 1065521786570-19reuv03qbdp37du41inh9gtd1s35g1j@developer.gserviceaccount.com

**Comment by tseaver** [comment]
#### Me

- tres.seaver@gmail.com
- `citric-celerity-697`
- 455332057385-54jtigust3p2kgrijp9csuna45a03vgc@developer.gserviceaccount.com

**Comment by mziccard** [comment]
#### Me

- marco.ziccard@gmail.com
- `gcloud-devel`
- 1016721519174-lnracm1bfhmsr1s2p3hkutlvn9hc422r@developer.gserviceaccount.com

#### `gcloud-java` System Tests

- `gcloud-devel`
- 1016721519174-b9thgn0hnv07b2g7jfvrgd81kcd8db9l@developer.gserviceaccount.com

**Comment by ajkannan** [comment]
#### Me

* ajay.kannan93@gmail.com
* hobbygen-1036
* account-3@hobbygen-1036.iam.gserviceaccount.com

**Comment by aozarov** [comment]
#### Me

* aozarov@gmail.com
* ozarov-javamrsample
* 189024820947-qf8ad7suttcpjenrvatpp9238vq7dndc@developer.gserviceaccount.com<br>
  189024820947-qf8ad7suttcpjenrvatpp9238vq7dndc@developer.gserviceaccount.com

**Comment by jskeet** [comment]
#### Me

* jonathan.skeet@gmail.com
* jonskeet-uberproject
* 15529003025-compute@developer.gserviceaccount.com

**Comment by mcgreevy** [comment]
mcgreevy@golang.org
project IDs for development: ace-world-840 , ace-world-841 , dark-throne-819

**Comment by okdave** [comment]
- djd@golang.org
- project for integration tests: dulcet-port-762
- project for dev: go-dave

**Comment by daspecster** [comment]
- daspecster@gmail.com
- ferrous-arena
- ferrous-arena-tests
- ferrous-arena@ferrous-arena.iam.gserviceaccount.com
- ferrous-arena-tests@ferrous-arena-tests.iam.gserviceaccount.com

**Comment by jdpedrie** [comment]
john@pedrie.com

Project ID for dev - jdpedrie-1279	
Service account email for dev - jdpedrie@jdpedrie-1279.iam.gserviceaccount.com

**Comment by quartzmo** [comment]
### Chris Smith

###### gmail address:

quartzmo@gmail.com

###### project ID for development:

bustling-kayak-91516

###### project ID for your project's tests:

helical-zone-771

###### service account email for development:

664476911263-rfrsgaitrs4niii0k60ns485cu4vgm2u@developer.gserviceaccount.com

###### service account email for your project's tests:

542339357638-cr0dserr2evg7sv1meghqeu703274f3h@developer.gserviceaccount.com

**Comment by jdpedrie** [comment]
## PHP Integration Tests Project

* **Project ID**: gcloud-php-integration-tests
* **Service Account Email**: gcloud-php-integration-tests@gcloud-php-integration-tests.iam.gserviceaccount.com
