### ISSUE TITLE
Cloud Contacts

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/google-cloud-common#74]
Like the reverse of #66, can we list good points of contact for the various cloud services? Folks we can ping in our PRs/issues or if we notice API bugs.

(Sorry if this was already answered somewhere, I couldn't find anything)
- BigQuery: 
- Bigtable: @lesv @sduskis
- Compute: 
- Datastore: @pcostell
- DLP: 
- DNS: @balajisam
- Language: 
- Logging: @filipjs
- Monitoring: 
- Prediction: 
- Pub/Sub:
- Resource Manager: @rae42 @charvesf
- Spanner: @vkedia
- Speech: 
- Storage: @jskeet @Capstan @aozarov @thobrla
- Translate: 
- Video Intelligence: 
- Vision:

**Comment by danoscarmike** [comment]
Closing as redundant.
