### ISSUE TITLE
Font + Page Sizing

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/google-cloud-common#75]
![screenshot_2016-02-07-09-12-07](https://cloud.githubusercontent.com/assets/723048/12872816/2071d70c-cd7b-11e5-824a-d9c636f85aa2.png)

This is Chrome on a Note 5. The arrow from the collapsible getting started is missing. Maybe not a font issue, but using a character outside utf8?

**Comment by callmehiphop** [comment]
@stephenplusplus this displays fine for me on my phone and when I emulate the page using Chrome devtools (although I don't see your particular model as an option). Is this something you'd be willing to tackle?

**Comment by stephenplusplus** [comment]
Yes!

**Comment by stephenplusplus** [comment]
@callmehiphop can you check again with this page: https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.24.0/storage/bucket

The params for createWriteStream are quite large. What's a reasonable solution here-- a responsive parameters table?

**Comment by callmehiphop** [comment]
Correct me if I'm wrong, that's always been an issue (old docs site as well?). I'm not sure if I understand what you mean by responsive parameters table, I've seen a few different strategies for displaying tables on mobile.

**Comment by stephenplusplus** [comment]
> Correct me if I'm wrong, that's always been an issue (old docs site as well?).

Does that matter?

> I'm not sure if I understand what you mean by responsive parameters table

Because the width is too narrow to display the table in its current fashion (it breaks the layout), I meant re-design the table at smaller viewports to switch it to a different style that won't break the layout.

> I've seen a few different strategies for displaying tables on mobile.

What are they? Let's pick the best one!

**Comment by callmehiphop** [comment]
> Does that matter?

Yes, because this issue is describing layout issues for a specific device. Responsive parameter tables would be a new feature, so it probably belongs in it's own issue so we don't derail this one.

**Comment by stephenplusplus** [comment]
The fix for this issue is a responsive table. That's why the layout is broken. It's broken in Chrome on your desktop, too.

**Comment by callmehiphop** [comment]
> The fix for this issue is a responsive table. That's why the layout is broken.

Your title and original description only mention character encoding and sizing on a Note 5. We didn't start discussing param tables until 20 minutes ago.

> It's broken in Chrome on your desktop, too.

Actually it seems fine on my desktop?

**Comment by stephenplusplus** [comment]
The issue describes a problem with the layout. The solution for the problem was yet to be discovered.

<img width="402" alt="screen shot 2016-02-09 at 12 03 41 pm" src="https://cloud.githubusercontent.com/assets/723048/12923856/5a000006-cf25-11e5-9609-e46996e1b3b8.png">

This is non-emulation mode. If you flip on emulation:

<img width="456" alt="screen shot 2016-02-09 at 12 07 18 pm" src="https://cloud.githubusercontent.com/assets/723048/12923933/b4c40a46-cf25-11e5-8a74-a33d0e9ef425.png">

Maybe responsive tables wouldn't fix this and it's something else? I'm still just trying to find out how to fix the layout issue.
