### ISSUE TITLE
Add Method Groups

### ISSUE THREAD

**Issue by blowmage** [googleapis/google-cloud-common#80]
In gcloud-ruby we have a couple instances where we define a method on a class, and another method with the same name on instances of the class. Right now we cannot differentiate between the methods in the angular app. All methods, whether instance methods or static/class methods are listed in one group. We suggest nesting methods in under a group with a name, so that we can differentiate.

This would also help differentiate constructor methods. Instead of using the `constructor` attribute, we could create a "Constructor" group and list the constructor method under it.

Update: This issue will cover both method types (language-defined) and groups/categories (user-defined):
- [ ] Add `method.metadata.type` to support language-based method types, such as constructor, instance, and class/static
- [ ] Add `method.metadata.group` or `method.metadata.category` to support arbitrary, user-generated groups of methods, such as the "Data", "Lifecycle", and "Table" categories

**Comment by callmehiphop** [comment]
SGTM, my only real question about this is how will it be laid out? Currently we provide a method list at the top of each API page, for users who want information about a particular method this feature is invaluable. How do we still provide this functionality while indicating the differences between various methods in a user friendly way?

**Comment by blowmage** [comment]
What we've done is show the method lists by group. For example, see our current docs for [BigQuery's Dataset](http://googlecloudplatform.github.io/gcloud-ruby/docs/v0.6.1/Gcloud/Bigquery/Dataset.html). We have multiple groups, of methods listed at the top of the page. And the page shows each group, and the methods contained in it, in order.

**Comment by callmehiphop** [comment]
Ah, gotcha, something like that could definitely work. Were you planning on creating a method group for each of the categories listed in that table? Or would additional configurations be needed in order to map them properly.

**Comment by blowmage** [comment]
One group per category.

**Comment by callmehiphop** [comment]
Cool, historically we've always displayed this list in the constructor section, do you feel like that's still an appropriate place for it? Or that it would be better suited before the constructor but after the API title/overview?

**Comment by blowmage** [comment]
This might be one of the ways in which ruby and javascript differ. We can place documentation on the class as well as the class's constructor method, so in ruby it makes more sense to list all methods after the class description. But in javascript the code construct is the constructor, so that gets more complicated.

**Comment by blowmage** [comment]
Also, gcloud-ruby has many classes where the constructor is we intentionally marked as private so it doesn't get documented. We guide users to use other methods to create instances of those classes, and to not use the class constructor.

**Comment by callmehiphop** [comment]
I'm fine with placing the list after the class description, my only real concern is that it's visible towards the top of the document.

**Comment by quartzmo** [comment]
@blowmage @callmehiphop I think it would be helpful to distinguish between:

* Arbitrary, user-generated groups of methods, such as the "Data", "Lifecycle", and "Table" categories  [BigQuery's Dataset](http://googlecloudplatform.github.io/gcloud-ruby/docs/v0.6.1/Gcloud/Bigquery/Dataset.html) (This might be `method.metadata.category`.)
* Language-based method types, such as constructor, instance, and class/static (This might be `method.metadata.type`.)

I believe these attributes are separate and unrelated.

The former is a nice-to-have feature, but without the instance vs class methods of the latter, our current gcloud-ruby docs are broken (Both `Gcloud.dns` and `Gcloud#dns` are [labeled with `#` and have the same id/anchor](http://quartzmo.github.io/gcloud-ruby/#/docs/master/gcloud).)

I would like to begin work today on a PR for the latter issue, but before I do, should I split this issue?

@callmehiphop Regarding these language-based method types, I was thinking that a new `method.metadata.type` attribute could be optional (just like `isConstructor` is currently optional), with a default value of `instance`.

So, would you prefer that I preserve [the existing behavior](https://github.com/GoogleCloudPlatform/gcloud-common/blob/master/site/src/app/service/service.html#L32-L33) that depends on the `method.metadata.isConstructor` boolean, or convert this logic to an underlying test for `method.metadata.type === 'constructor'`? If I convert it, merging the PR will require all platforms to immediately add `"type": "constructor",` to constructor methods.

**Comment by callmehiphop** [comment]
I might have misunderstood the original purpose of method groups.. Based on @blowmage's gist, I thought we were going to use them to distinguish between constructor/static/instance/etc. Is that actually incorrect?

**Comment by quartzmo** [comment]
I am hoping to clarify that method *types* (such as "instance") should be identified separately from method *categories* (user-defined, such as "Lifecycle"). In Ruby's RDoc, the `:category:` tag allows you to group methods, and I know this is a feature that @blowmage wants. I want to caution that this proposal for groups should not attempt to do both.

**Comment by blowmage** [comment]
I think that if there were method groups, we could get away without having a method `type` value, (constructor, instance, static/class, etc.). But Chris is correct that it does not preclude having both. I am not opposed to having a method type on in the JSON.

**Comment by quartzmo** [comment]
@blowmage Thanks for seeing it that way, it just feels cleaner to me to keep these two things separate.

**Comment by callmehiphop** [comment]
Sounds fine to me!

**Comment by quartzmo** [comment]
I think this issue primarily describes the user-defined categories, so I will create a new issue for language-defined method types.

**Comment by quartzmo** [comment]
Actually, sorry for the confusion, I'll just append a checklist to the description.

**Comment by quartzmo** [comment]
@callmehiphop Regarding these language-based method types, I was thinking that a new `method.metadata.type` attribute could be optional (just like `isConstructor` is currently optional), with a default value of `instance`.

So, would you prefer that I preserve [the existing behavior](https://github.com/GoogleCloudPlatform/gcloud-common/blob/master/site/src/app/service/service.html#L32-L33) that depends on the `method.metadata.isConstructor` boolean, or convert this logic to an underlying test for `method.metadata.type === 'constructor'`? If I convert it, merging the PR will require all platforms to immediately add `"type": "constructor",` to constructor methods.
