### ISSUE TITLE
Add namespace navigation to Code Constucts JSON

### ISSUE THREAD

**Issue by blowmage** [googleapis/google-cloud-common#83]
Ruby code constructs are organized in a heirarchy, but there is no way in the current JSON to document this. We suggest adding `parent` and `children` attributes that list the code construct above and below. Being able to navigate up and down the namespace is very important for ruby developers. We expect this feature will also be useful for other languages.

For example, the class `Gcloud::Bigquery::Job` is nested under the module `Gcloud::Bigquery`, and has the class `Gcloud::Bigquery::Job::List` as a child.

**Comment by callmehiphop** [comment]
Could you please provide an example of what the JSON would look like?

**Comment by blowmage** [comment]
I see two main options for this. First, all code constructs are listed in a flat array, side-by-side, and have a `parent` attribute who's value is the unique ID of the parent code construct, and a `children` attribute which is an array of the unique IDs of the child code constructs. I've [updated my gist](https://gist.github.com/blowmage/13be352f40ee7ac5ee48#file-object-json-L8-L9) to demonstrate this. I think this option is the best since it allows for the easiest lookup of a code construct by the ID.

Second, the code constructs could be in a nested tree structure, where the parent and child relationships are determined by the tree structure. I don't like this option as much, but it is certainly viable.
