### ISSUE TITLE
Add inheritance to Code Constucts JSON

### ISSUE THREAD

**Issue by blowmage** [googleapis/google-cloud-common#84]
Ruby code constructs can inherit from other constructs. The current JSON offers no mechanism to document this. We suggest adding an `inherits` attribute that would list the parent class and any modules that are used in the code construct definition. We expect this feature will also be used by other languages.

We might also consider an `inherited_by` attribute that lists the other code constructs in the version that inherit the code construct being shown.

**Comment by callmehiphop** [comment]
SGTM, any proposals for how to display this information? I can't speak for any library other than Node, but we do use multiple inheritance.

**Comment by blowmage** [comment]
I don't have any proposals for the UI, but I assume there are several ways to convey this info.

**Comment by callmehiphop** [comment]
In JavaScript sometimes we prefix `#` to signify that a method is an instance method. Perhaps the easiest path would be to prepend certain characters to the method names.

@stephenplusplus thoughts?

**Comment by blowmage** [comment]
@callmehiphop Was this comment meant for #79?

**Comment by callmehiphop** [comment]
Actually it was meant for #80, my bad!

**Comment by callmehiphop** [comment]
@stephenplusplus any design thoughts on how to display this information?
