### ISSUE TITLE
Add API Reference

### ISSUE THREAD

**Issue by blowmage** [googleapis/google-cloud-common#85]
Assuming #78 is accepted, we suggest adding a new feature that will list all code constructs and methods in the version. The gcloud-ruby documentation does this currently. It has the [curated side navigation](http://googlecloudplatform.github.io/gcloud-ruby/docs/v0.6.1/), and an [API Reference](http://googlecloudplatform.github.io/gcloud-ruby/docs/v0.6.1/reference.html) with a full listing of all the costructs and methods. This is very useful for gcloud-ruby, which has many more code constructs than can fit in the side navigation.

**Comment by stephenplusplus** [comment]
I think this relates to what I was asking here: https://github.com/GoogleCloudPlatform/gcloud-common/issues/78#issuecomment-181445609

Is a happy alternative to a new API reference page just placing the "extra" constructs and methods separate from the common case ones?:

```
API
> gcloud
> BigQuery
  > Dataset
  > Table
  > Job
  > API
    > ApiError
    > CopyJob
    > Data
    > Error
    > ExtractJob
    > ...
> Compute
> DNS
...
```

I think that-- or something like it-- gives the user a quicker way to first find the thing they're looking for, then go back and forth between it and others.

**Comment by quartzmo** [comment]
@stephenplusplus I think what @blowmage calls an API Reference, I think of as a good ole-fashioned *index*. Our current [gh-pages API Reference](http://googlecloudplatform.github.io/gcloud-ruby/docs/v0.6.1/reference.html) does *not* provide a global listing of all public methods, but [our docs on rubydoc.info](http://www.rubydoc.info/gems/gcloud) provide this when you click `Methods` in the left nav. Pretty handy when you know a method name but can't remember where it is!

**Comment by callmehiphop** [comment]
@quartzmo based on the [version gist](https://gist.github.com/blowmage/13be352f40ee7ac5ee48#file-version-json) I assumed this would be a new feature that would essentially mimic the functionality on rubydocs.

It's probably worth mentioning that we've been discussing similar functionality on a [gcloud-node issue](https://github.com/GoogleCloudPlatform/gcloud-node/issues/1084), so I think that @stephenplusplus was trying to start a conversation about how we can implement an API Reference in an intuitive fashion that works for everyone.

**Comment by blowmage** [comment]
We need to preserve the behavior of our current navigation, which presents a curated view into the library. Adding new links in the navigation won't be consistent with the current approach. Therefore I don't think a new API section in the navigation is a good solution.

I would be happy to discuss a less scary term than "API Reference", and ways to combine this issue with #86. I think there is something to these two issues that will elevate the current UX even more.

**Comment by stephenplusplus** [comment]
I think there's still a way to do that, having that secondary API menu be collapsible.

**Comment by callmehiphop** [comment]
If it's imperative that you preserve the behavior of your current navigation, it's probably fine that we deviate here. Since the JSON can dictate the contents available within the navigation component, I see no reason why you can't have an item that the other sites do not.
