### ISSUE TITLE
Add Search

### ISSUE THREAD

**Issue by blowmage** [googleapis/google-cloud-common#86]
Search is not currently possible with the current JSON structure due to how the code constructs are not all available until all the JSON is loaded. Assuming #78 is accepted, we would have all code constructs and method available via the version manifest to search on. We think that search will become a very important feature for finding and navigating the documentation.

**Comment by stephenplusplus** [comment]
Good call, search is important. I have to say, though, I've noticed a huge perf increase since we switched to multiple files. I have a feeling that is the fault of our app trying to do too much while parsing the file.

Let's make a to-do to profile the app once we have a PR for this feature.

**Comment by blowmage** [comment]
I agree that javascript heavy frontons get into trouble when they do too much. It might be quicker if we had a server-side search service we could call. However most static HTML dumps of code documentation contain a "manifest" of all code constructs and methods that enable fast search. I think this feature is possible with relatively minor changes. For example, here is the [javascript for ruby's minitest](http://docs.seattlerb.org/minitest/js/search_index.js) that powers search. Putting a slimmed down version of all code constructs and methods in a version manifest will enable this type of functionality, and shouldn't add too much bloat.

For reference, [here is an attempt](https://gist.github.com/blowmage/13be352f40ee7ac5ee48) at a main, version, and object JSON data structures that should allow search.

**Comment by callmehiphop** [comment]
Since none of the sites currently implement search (some one correct me if that is wrong) I'm going to say this feature is somewhat less important at the moment. I can definitely see value in search for the future, but before we add new features we should first prioritize getting the various libraries integrated with the shared docs site.

**Comment by blowmage** [comment]
I'm fine with this issue being deemed less important. I've always wanted to get search working on our existing docs, but never took the time.

**Comment by quartzmo** [comment]
As long as Google search can be used effectively with the site, I also find internal search to be a lower priority.
