### ISSUE TITLE
Guide links redirect loop

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/google-cloud-common#89]
Links such as: https://googlecloudplatform.github.io/gcloud-node/#/contributing look like they're caught in a redirect loop and don't end up anywhere.

Ideally, these could be routed to https://googlecloudplatform.github.io/gcloud-node/#/docs/{latest version}/guides/contributing

**Comment by callmehiphop** [comment]
I think If we can help it, we should avoid supporting legacy links. None of the gcloud-* sites follow the same pattern for URLs, so while this might be good for node, it offers no benefit for anyone else. Instead I think we should consider trying to update old links.

**Comment by stephenplusplus** [comment]
It's not really about supporting legacy links, it's just a logical URL for a page on the website. It should offer the same benefit for any gcloud-* that has guides.

**Comment by stephenplusplus** [comment]
@quartzmo @jgeewax any thoughts on this?

Should we have aliases:
```
http://googlecloudplatform.github.io/gcloud-*/#/contributing
```

Or strictly versioned paths?:
```
http://googlecloudplatform.github.io/gcloud-*/#/docs/v1.0.3/guides/contributing
```

**Comment by jgeewax** [comment]
Seems like contributions will always be against the latest version of the
code, right?

Any other guides that would be directly related to a specific version?

**Comment by stephenplusplus** [comment]
Any guide could have random bits in there that might be tied to a version, like "Just set these env vars" or "First install ___ locally" which might later not be correct. Supporting the contributing guides for older versions of our code doesn't make too much since, but afaik we don't distinguish between guides we want to version and guides we don't.

So a better example could be the Authentication guide, where it is more likely to be important for someone to access the guide specific to the version they're running.

The shorthand aliases would just be used to point to the latest.

**Comment by jgeewax** [comment]
OK - so version the guides, and then if missing, go with latest? SGTM

**Comment by callmehiphop** [comment]
> afaik we don't distinguish between guides we want to version and guides we don't

This is correct, however this might be an easy feature to support (maybe) once we [split the manifest up](https://github.com/GoogleCloudPlatform/gcloud-common/issues/77).

**Comment by quartzmo** [comment]
I'm not sure if this is related, or if instead I should open a new issue:

Navigating (via an outside link) to the path for a package, _without a version_, results in an infinite redirect.

https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-bigquery/
https://googlecloudplatform.github.io/google-cloud-node/#/docs/bigquery/

I also built the site from PR #182 just to see if that fixes it, but it does not:

https://quartzmo.github.io/google-cloud-ruby/#/docs/google-cloud-bigquery/

**Comment by callmehiphop** [comment]
@quartzmo I think that's an angular-ui-router quirk :( looks like when it sees the trailing slash it assumes the version is present and null.

**Comment by quartzmo** [comment]
@callmehiphop Should I open a new issue or is this one good? I originally wrote links from our READMEs to these paths (without version), but I had to change them all to `/master/` version after we received GoogleCloudPlatform/google-cloud-ruby#865.

**Comment by quartzmo** [comment]
Sorry, I was mistaken, it was while looking into the issue above that I discovered the infinite redirect on my own, then worked around it with  GoogleCloudPlatform/google-cloud-ruby#872.

**Comment by callmehiphop** [comment]
@quartzmo I actually took a crack at it in #182.
