### ISSUE TITLE
New issue templates

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/google-cloud-common#96]
Relates to #39 

It looks like we [might be getting a new feature](https://github.com/dear-github/dear-github/issues/125) from GitHub that allows us to default content inside of the new issue box. We can probably host a standard one here that each client lib can branch off of as necessary.

**Comment by blowmage** [comment]
This seems like a useful feature. I like how [react-router is using it](https://github.com/reactjs/react-router/issues/new) by putting information in a comment.

**Comment by jgeewax** [comment]
Just saw that on HN --- yes , we shouldn't definitely do that. It seems we
just add a file...
https://github.com/owncloud/core/blob/master/issue_template.md
